/*
Copyright DHTMLX LTD. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/dhtmlx=function(a){for(var b in a)dhtmlx[b]=a[b];return dhtmlx};dhtmlx.extend_api=function(a,b,c){var d=window[a];if(d)window[a]=function(a){if(a&&typeof a=="object"&&!a.tagName){var c=d.apply(this,b._init?b._init(a):arguments),h;for(h in dhtmlx)if(b[h])this[b[h]](dhtmlx[h]);for(h in a)if(b[h])this[b[h]](a[h]);else h.indexOf("on")==0&&this.attachEvent(h,a[h])}else c=d.apply(this,arguments);b._patch&&b._patch(this);return c||this},window[a].prototype=d.prototype,c&&dhtmlXHeir(window[a].prototype,c)};
dhtmlxAjax={get:function(a,b){var c=new dtmlXMLLoaderObject(!0);c.async=arguments.length<3;c.waitCall=b;c.loadXML(a);return c},post:function(a,b,c){var d=new dtmlXMLLoaderObject(!0);d.async=arguments.length<4;d.waitCall=c;d.loadXML(a,!0,b);return d},getSync:function(a){return this.get(a,null,!0)},postSync:function(a,b){return this.post(a,b,null,!0)}};
function dtmlXMLLoaderObject(a,b,c,d){this.xmlDoc="";this.async=typeof c!="undefined"?c:!0;this.onloadAction=a||null;this.mainObject=b||null;this.waitCall=null;this.rSeed=d||!1;return this}
dtmlXMLLoaderObject.prototype.waitLoadFunction=function(a){var b=!0;return this.check=function(){if(a&&a.onloadAction!=null&&(!a.xmlDoc.readyState||a.xmlDoc.readyState==4)&&b){b=!1;if(typeof a.onloadAction=="function")a.onloadAction(a.mainObject,null,null,null,a);if(a.waitCall)a.waitCall.call(this,a),a.waitCall=null}}};
dtmlXMLLoaderObject.prototype.getXMLTopNode=function(a,b){if(this.xmlDoc.responseXML){var c=this.xmlDoc.responseXML.getElementsByTagName(a);c.length==0&&a.indexOf(":")!=-1&&(c=this.xmlDoc.responseXML.getElementsByTagName(a.split(":")[1]));var d=c[0]}else d=this.xmlDoc.documentElement;if(d)return this._retry=!1,d;if(_isIE&&!this._retry){var e=this.xmlDoc.responseText,b=this.xmlDoc;this._retry=!0;this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM");this.xmlDoc.async=!1;this.xmlDoc.loadXML(e);return this.getXMLTopNode(a,
b)}dhtmlxError.throwError("LoadXML","Incorrect XML",[b||this.xmlDoc,this.mainObject]);return document.createElement("DIV")};
dtmlXMLLoaderObject.prototype.loadXMLString=function(a){if(_isIE)this.xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),this.xmlDoc.async=this.async,this.xmlDoc.onreadystatechange=function(){},this.xmlDoc.loadXML(a);else{var b=new DOMParser;this.xmlDoc=b.parseFromString(a,"text/xml")}if(this.onloadAction)this.onloadAction(this.mainObject,null,null,null,this);if(this.waitCall)this.waitCall(),this.waitCall=null};
dtmlXMLLoaderObject.prototype.loadXML=function(a,b,c,d){this.rSeed&&(a+=(a.indexOf("?")!=-1?"&":"?")+"a_dhx_rSeed="+(new Date).valueOf());this.filePath=a;this.xmlDoc=!_isIE&&window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");if(this.async)this.xmlDoc.onreadystatechange=new this.waitLoadFunction(this);this.xmlDoc.open(b?"POST":"GET",a,this.async);d?(this.xmlDoc.setRequestHeader("User-Agent","dhtmlxRPC v0.1 ("+navigator.userAgent+")"),this.xmlDoc.setRequestHeader("Content-type",
"text/xml")):b&&this.xmlDoc.setRequestHeader("Content-type","application/x-www-form-urlencoded");this.xmlDoc.setRequestHeader("X-Requested-With","XMLHttpRequest");this.xmlDoc.send(c);this.async||(new this.waitLoadFunction(this))()};
dtmlXMLLoaderObject.prototype.destructor=function(){return this.setXSLParamValue=this.getXMLTopNode=this.xmlNodeToJSON=this.doSerialization=this.loadXMLString=this.loadXML=this.doXSLTransToString=this.doXSLTransToObject=this.doXPathOpera=this.doXPath=this.xmlDoc=this.mainObject=this.onloadAction=this.filePath=this.rSeed=this.async=this._retry=this._getAllNamedChilds=this._filterXPath=null};
dtmlXMLLoaderObject.prototype.xmlNodeToJSON=function(a){for(var b={},c=0;c<a.attributes.length;c++)b[a.attributes[c].name]=a.attributes[c].value;b._tagvalue=a.firstChild?a.firstChild.nodeValue:"";for(c=0;c<a.childNodes.length;c++){var d=a.childNodes[c].tagName;d&&(b[d]||(b[d]=[]),b[d].push(this.xmlNodeToJSON(a.childNodes[c])))}return b};function callerFunction(a,b){return this.handler=function(c){if(!c)c=window.event;a(c,b);return!0}}function getAbsoluteLeft(a){return getOffset(a).left}
function getAbsoluteTop(a){return getOffset(a).top}function getOffsetSum(a){for(var b=0,c=0;a;)b+=parseInt(a.offsetTop),c+=parseInt(a.offsetLeft),a=a.offsetParent;return{top:b,left:c}}
function getOffsetRect(a){var b=a.getBoundingClientRect(),c=document.body,d=document.documentElement,e=window.pageYOffset||d.scrollTop||c.scrollTop,g=window.pageXOffset||d.scrollLeft||c.scrollLeft,h=d.clientTop||c.clientTop||0,f=d.clientLeft||c.clientLeft||0,i=b.top+e-h,j=b.left+g-f;return{top:Math.round(i),left:Math.round(j)}}function getOffset(a){return a.getBoundingClientRect?getOffsetRect(a):getOffsetSum(a)}
function convertStringToBoolean(a){typeof a=="string"&&(a=a.toLowerCase());switch(a){case "1":case "true":case "yes":case "y":case 1:case !0:return!0;default:return!1}}function getUrlSymbol(a){return a.indexOf("?")!=-1?"&":"?"}function dhtmlDragAndDropObject(){if(window.dhtmlDragAndDrop)return window.dhtmlDragAndDrop;this.dragStartObject=this.dragStartNode=this.dragNode=this.lastLanding=0;this.tempDOMM=this.tempDOMU=null;this.waitDrag=0;window.dhtmlDragAndDrop=this;return this}
dhtmlDragAndDropObject.prototype.removeDraggableItem=function(a){a.onmousedown=null;a.dragStarter=null;a.dragLanding=null};dhtmlDragAndDropObject.prototype.addDraggableItem=function(a,b){a.onmousedown=this.preCreateDragCopy;a.dragStarter=b;this.addDragLanding(a,b)};dhtmlDragAndDropObject.prototype.addDragLanding=function(a,b){a.dragLanding=b};
dhtmlDragAndDropObject.prototype.preCreateDragCopy=function(a){if(!((a||window.event)&&(a||event).button==2)){if(window.dhtmlDragAndDrop.waitDrag)return window.dhtmlDragAndDrop.waitDrag=0,document.body.onmouseup=window.dhtmlDragAndDrop.tempDOMU,document.body.onmousemove=window.dhtmlDragAndDrop.tempDOMM,!1;window.dhtmlDragAndDrop.dragNode&&window.dhtmlDragAndDrop.stopDrag(a);window.dhtmlDragAndDrop.waitDrag=1;window.dhtmlDragAndDrop.tempDOMU=document.body.onmouseup;window.dhtmlDragAndDrop.tempDOMM=
document.body.onmousemove;window.dhtmlDragAndDrop.dragStartNode=this;window.dhtmlDragAndDrop.dragStartObject=this.dragStarter;document.body.onmouseup=window.dhtmlDragAndDrop.preCreateDragCopy;document.body.onmousemove=window.dhtmlDragAndDrop.callDrag;window.dhtmlDragAndDrop.downtime=(new Date).valueOf();a&&a.preventDefault&&a.preventDefault();return!1}};
dhtmlDragAndDropObject.prototype.callDrag=function(a){if(!a)a=window.event;dragger=window.dhtmlDragAndDrop;if(!((new Date).valueOf()-dragger.downtime<100)){if(!dragger.dragNode)if(dragger.waitDrag){dragger.dragNode=dragger.dragStartObject._createDragNode(dragger.dragStartNode,a);if(!dragger.dragNode)return dragger.stopDrag();dragger.dragNode.onselectstart=function(){return!1};dragger.gldragNode=dragger.dragNode;document.body.appendChild(dragger.dragNode);document.body.onmouseup=dragger.stopDrag;dragger.waitDrag=
0;dragger.dragNode.pWindow=window;dragger.initFrameRoute()}else return dragger.stopDrag(a,!0);if(dragger.dragNode.parentNode!=window.document.body&&dragger.gldragNode){var b=dragger.gldragNode;if(dragger.gldragNode.old)b=dragger.gldragNode.old;b.parentNode.removeChild(b);var c=dragger.dragNode.pWindow;b.pWindow&&b.pWindow.dhtmlDragAndDrop.lastLanding&&b.pWindow.dhtmlDragAndDrop.lastLanding.dragLanding._dragOut(b.pWindow.dhtmlDragAndDrop.lastLanding);if(_isIE){var d=document.createElement("Div");d.innerHTML=
dragger.dragNode.outerHTML;dragger.dragNode=d.childNodes[0]}else dragger.dragNode=dragger.dragNode.cloneNode(!0);dragger.dragNode.pWindow=window;dragger.gldragNode.old=dragger.dragNode;document.body.appendChild(dragger.dragNode);c.dhtmlDragAndDrop.dragNode=dragger.dragNode}dragger.dragNode.style.left=a.clientX+15+(dragger.fx?dragger.fx*-1:0)+(document.body.scrollLeft||document.documentElement.scrollLeft)+"px";dragger.dragNode.style.top=a.clientY+3+(dragger.fy?dragger.fy*-1:0)+(document.body.scrollTop||
document.documentElement.scrollTop)+"px";var e=a.srcElement?a.srcElement:a.target;dragger.checkLanding(e,a)}};dhtmlDragAndDropObject.prototype.calculateFramePosition=function(a){if(window.name){for(var b=parent.frames[window.name].frameElement.offsetParent,c=0,d=0;b;)c+=b.offsetLeft,d+=b.offsetTop,b=b.offsetParent;if(parent.dhtmlDragAndDrop){var e=parent.dhtmlDragAndDrop.calculateFramePosition(1);c+=e.split("_")[0]*1;d+=e.split("_")[1]*1}if(a)return c+"_"+d;else this.fx=c;this.fy=d}return"0_0"};
dhtmlDragAndDropObject.prototype.checkLanding=function(a,b){a&&a.dragLanding?(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding),this.lastLanding=a,this.lastLanding=this.lastLanding.dragLanding._dragIn(this.lastLanding,this.dragStartNode,b.clientX,b.clientY,b),this.lastLanding_scr=_isIE?b.srcElement:b.target):a&&a.tagName!="BODY"?this.checkLanding(a.parentNode,b):(this.lastLanding&&this.lastLanding.dragLanding._dragOut(this.lastLanding,b.clientX,b.clientY,b),this.lastLanding=
0,this._onNotFound&&this._onNotFound())};
dhtmlDragAndDropObject.prototype.stopDrag=function(a,b){dragger=window.dhtmlDragAndDrop;if(!b){dragger.stopFrameRoute();var c=dragger.lastLanding;dragger.lastLanding=null;c&&c.dragLanding._drag(dragger.dragStartNode,dragger.dragStartObject,c,_isIE?event.srcElement:a.target)}dragger.lastLanding=null;dragger.dragNode&&dragger.dragNode.parentNode==document.body&&dragger.dragNode.parentNode.removeChild(dragger.dragNode);dragger.dragNode=0;dragger.gldragNode=0;dragger.fx=0;dragger.fy=0;dragger.dragStartNode=
0;dragger.dragStartObject=0;document.body.onmouseup=dragger.tempDOMU;document.body.onmousemove=dragger.tempDOMM;dragger.tempDOMU=null;dragger.tempDOMM=null;dragger.waitDrag=0};dhtmlDragAndDropObject.prototype.stopFrameRoute=function(a){a&&window.dhtmlDragAndDrop.stopDrag(1,1);for(var b=0;b<window.frames.length;b++)try{window.frames[b]!=a&&window.frames[b].dhtmlDragAndDrop&&window.frames[b].dhtmlDragAndDrop.stopFrameRoute(window)}catch(c){}try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=a&&parent.dhtmlDragAndDrop.stopFrameRoute(window)}catch(d){}};
dhtmlDragAndDropObject.prototype.initFrameRoute=function(a,b){if(a)window.dhtmlDragAndDrop.preCreateDragCopy(),window.dhtmlDragAndDrop.dragStartNode=a.dhtmlDragAndDrop.dragStartNode,window.dhtmlDragAndDrop.dragStartObject=a.dhtmlDragAndDrop.dragStartObject,window.dhtmlDragAndDrop.dragNode=a.dhtmlDragAndDrop.dragNode,window.dhtmlDragAndDrop.gldragNode=a.dhtmlDragAndDrop.dragNode,window.document.body.onmouseup=window.dhtmlDragAndDrop.stopDrag,window.waitDrag=0,!_isIE&&b&&(!_isFF||_FFrv<1.8)&&window.dhtmlDragAndDrop.calculateFramePosition();
try{parent.dhtmlDragAndDrop&&parent!=window&&parent!=a&&parent.dhtmlDragAndDrop.initFrameRoute(window)}catch(c){}for(var d=0;d<window.frames.length;d++)try{window.frames[d]!=a&&window.frames[d].dhtmlDragAndDrop&&window.frames[d].dhtmlDragAndDrop.initFrameRoute(window,!a||b?1:0)}catch(e){}};_OperaRv=_KHTMLrv=_FFrv=_isChrome=_isMacOS=_isKHTML=_isOpera=_isIE=_isFF=!1;navigator.userAgent.indexOf("Macintosh")!=-1&&(_isMacOS=!0);navigator.userAgent.toLowerCase().indexOf("chrome")>-1&&(_isChrome=!0);
navigator.userAgent.indexOf("Safari")!=-1||navigator.userAgent.indexOf("Konqueror")!=-1?(_KHTMLrv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Safari")+7,5)),_KHTMLrv>525?(_isFF=!0,_FFrv=1.9):_isKHTML=!0):navigator.userAgent.indexOf("Opera")!=-1?(_isOpera=!0,_OperaRv=parseFloat(navigator.userAgent.substr(navigator.userAgent.indexOf("Opera")+6,3))):navigator.appName.indexOf("Microsoft")!=-1?(_isIE=!0,navigator.appVersion.indexOf("MSIE 8.0")!=-1&&document.compatMode!="BackCompat"&&
(_isIE=8),navigator.appVersion.indexOf("MSIE 9.0")!=-1&&document.compatMode!="BackCompat"&&(_isIE=8)):(_isFF=!0,_FFrv=parseFloat(navigator.userAgent.split("rv:")[1]));
dtmlXMLLoaderObject.prototype.doXPath=function(a,b,c,d){if(_isKHTML||!_isIE&&!window.XPathResult)return this.doXPathOpera(a,b);if(_isIE)return b||(b=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML),b||dhtmlxError.throwError("LoadXML","Incorrect XML",[b||this.xmlDoc,this.mainObject]),c!=null&&b.setProperty("SelectionNamespaces","xmlns:xsl='"+c+"'"),d=="single"?b.selectSingleNode(a):b.selectNodes(a)||[];else{var e=b;b||(b=this.xmlDoc.nodeName?this.xmlDoc:this.xmlDoc.responseXML);b||dhtmlxError.throwError("LoadXML",
"Incorrect XML",[b||this.xmlDoc,this.mainObject]);b.nodeName.indexOf("document")!=-1?e=b:(e=b,b=b.ownerDocument);var g=XPathResult.ANY_TYPE;if(d=="single")g=XPathResult.FIRST_ORDERED_NODE_TYPE;var h=[],f=b.evaluate(a,e,function(){return c},g,null);if(g==XPathResult.FIRST_ORDERED_NODE_TYPE)return f.singleNodeValue;for(var i=f.iterateNext();i;)h[h.length]=i,i=f.iterateNext();return h}};function n(){if(!this.catches)this.catches=[];return this}n.prototype.catchError=function(a,b){this.catches[a]=b};
n.prototype.throwError=function(a,b,c){if(this.catches[a])return this.catches[a](a,b,c);if(this.catches.ALL)return this.catches.ALL(a,b,c);alert("Error type: "+a+"\nDescription: "+b);return null};window.dhtmlxError=new n;
dtmlXMLLoaderObject.prototype.doXPathOpera=function(a,b){var c=a.replace(/[\/]+/gi,"/").split("/"),d=null,e=1;if(!c.length)return[];if(c[0]==".")d=[b];else if(c[0]=="")d=(this.xmlDoc.responseXML||this.xmlDoc).getElementsByTagName(c[e].replace(/\[[^\]]*\]/g,"")),e++;else return[];for(;e<c.length;e++)d=this._getAllNamedChilds(d,c[e]);c[e-1].indexOf("[")!=-1&&(d=this._filterXPath(d,c[e-1]));return d};
dtmlXMLLoaderObject.prototype._filterXPath=function(a,b){for(var c=[],b=b.replace(/[^\[]*\[\@/g,"").replace(/[\[\]\@]*/g,""),d=0;d<a.length;d++)a[d].getAttribute(b)&&(c[c.length]=a[d]);return c};
dtmlXMLLoaderObject.prototype._getAllNamedChilds=function(a,b){var c=[];_isKHTML&&(b=b.toUpperCase());for(var d=0;d<a.length;d++)for(var e=0;e<a[d].childNodes.length;e++)_isKHTML?a[d].childNodes[e].tagName&&a[d].childNodes[e].tagName.toUpperCase()==b&&(c[c.length]=a[d].childNodes[e]):a[d].childNodes[e].tagName==b&&(c[c.length]=a[d].childNodes[e]);return c};function dhtmlXHeir(a,b){for(var c in b)typeof b[c]=="function"&&(a[c]=b[c]);return a}
function dhtmlxEvent(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)}dtmlXMLLoaderObject.prototype.xslDoc=null;dtmlXMLLoaderObject.prototype.setXSLParamValue=function(a,b,c){if(!c)c=this.xslDoc;if(c.responseXML)c=c.responseXML;var d=this.doXPath("/xsl:stylesheet/xsl:variable[@name='"+a+"']",c,"http://www.w3.org/1999/XSL/Transform","single");if(d!=null)d.firstChild.nodeValue=b};
dtmlXMLLoaderObject.prototype.doXSLTransToObject=function(a,b){if(!a)a=this.xslDoc;if(a.responseXML)a=a.responseXML;if(!b)b=this.xmlDoc;if(b.responseXML)b=b.responseXML;if(_isIE){d=new ActiveXObject("Msxml2.DOMDocument.3.0");try{b.transformNodeToObject(a,d)}catch(c){d=b.transformNode(a)}}else{if(!this.XSLProcessor)this.XSLProcessor=new XSLTProcessor,this.XSLProcessor.importStylesheet(a);var d=this.XSLProcessor.transformToDocument(b)}return d};
dtmlXMLLoaderObject.prototype.doXSLTransToString=function(a,b){var c=this.doXSLTransToObject(a,b);return typeof c=="string"?c:this.doSerialization(c)};dtmlXMLLoaderObject.prototype.doSerialization=function(a){if(!a)a=this.xmlDoc;if(a.responseXML)a=a.responseXML;if(_isIE)return a.xml;else{var b=new XMLSerializer;return b.serializeToString(a)}};
dhtmlxEventable=function(a){a.attachEvent=function(a,c,d){a="ev_"+a.toLowerCase();this[a]||(this[a]=new this.eventCatcher(d||this));return a+":"+this[a].addEvent(c)};a.callEvent=function(a,c){a="ev_"+a.toLowerCase();return this[a]?this[a].apply(this,c):!0};a.checkEvent=function(a){return!!this["ev_"+a.toLowerCase()]};a.eventCatcher=function(a){var c=[],d=function(){for(var d=!0,g=0;g<c.length;g++)if(c[g]!=null)var h=c[g].apply(a,arguments),d=d&&h;return d};d.addEvent=function(a){typeof a!="function"&&
(a=eval(a));return a?c.push(a)-1:!1};d.removeEvent=function(a){c[a]=null};return d};a.detachEvent=function(a){if(a!=!1){var c=a.split(":");this[c[0]].removeEvent(c[1])}};a.detachAllEvents=function(){for(var a in this)a.indexOf("ev_")==0&&delete this[a]}};
(function(){var a=dhtmlx.message=function(b,c,d,e){if(!a.area)a.area=document.createElement("DIV"),a.area.style.cssText="position:absolute;right:5px;width:250px;z-index:100;",a.area.className="dhtmlx_message_area",a.area.style[a.defPosition]="5px",document.body.appendChild(a.area);typeof b!="object"&&(b={text:b,type:c,lifetime:d,id:e});b.type=b.type||"info";b.id=b.id||a.uid();b.lifetime=b.lifetime||a.defTimeout;a.hide(b.id);var g=document.createElement("DIV");g.style.cssText="border-radius:4px; padding:4px 4px 4px 20px;background-color:#FFFFCC;font-size:12px;font-family:Tahoma;color:navy;z-index: 10000;margin:5px;border:1px solid lightgrey;";
g.innerHTML=b.text;g.className=b.type;a.defPosition=="bottom"&&a.area.firstChild?a.area.insertBefore(g,a.area.firstChild):a.area.appendChild(g);a.timers[b.id]=window.setTimeout(function(){a.hide(b.id)},b.lifetime);a.pull[b.id]=g;return b.id};a.defTimeout=4E3;a.defPosition="top";a.pull={};a.timers={};a.seed=(new Date).valueOf();a.uid=function(){return a.seed++};a.hideAll=function(){for(var b in a.pull)a.hide(b)};a.hide=function(b){var c=a.pull[b];c&&c.parentNode&&(c.parentNode.removeChild(c),window.clearTimeout(a.timers[b]),
delete a.pull[b])}})();
function dhtmlXCalendarObject(a,b){this.i={};this.uid=function(){if(!this.uidd)this.uidd=(new Date).getTime();return this.uidd++};var c=null,d=typeof a=="string"?document.getElementById(a):a;d&&typeof d=="object"&&d.tagName&&String(d.tagName).toLowerCase()!="input"&&(c=d);d=null;if(typeof a!="object"||!a.length)a=[a];for(var e=0;e<a.length;e++)typeof a[e]=="string"&&(a[e]=document.getElementById(a[e])||null),a[e]!=null&&a[e].tagName&&String(a[e].tagName).toLowerCase()=="input"&&(this.i[this.uid()]=
a[e]),a[e]=null;this.skin=b||"dhx_skyblue";this.setSkin=function(a){this.skin=a;this.base.className="dhtmlxcalendar_container dhtmlxcalendar_skin_"+this.skin};this.base=document.createElement("DIV");this.base.className="dhtmlxcalendar_container";this.base.style.display="none";c!=null?(this._hasParent=!0,c.appendChild(this.base),c=null):document.body.appendChild(this.base);this.setParent=function(a){this._hasParent&&(typeof a=="object"?a.appendChild(this.base):typeof a=="string"&&document.getElementById(a).appendChild(this.base))};
this.setSkin(this.skin);this.base.onclick=function(a){a=a||event;a.cancelBubble=!0};this.loadUserLanguage=function(a){if(this.langData[a]&&(this.lang=a,this.setWeekStartDay(this.langData[this.lang].weekstart),this.msCont))for(var b=0,c=0;c<this.msCont.childNodes.length;c++)for(var d=0;d<this.msCont.childNodes[c].childNodes.length;d++)this.msCont.childNodes[c].childNodes[d].innerHTML=this.langData[this.lang].monthesSNames[b++]};this.contMonth=document.createElement("DIV");this.contMonth.className=
"dhtmlxcalendar_month_cont";this.contMonth.onselectstart=function(a){a=a||event;a.cancelBubble=!0;return a.returnValue=!1};this.base.appendChild(this.contMonth);var g=document.createElement("UL");g.className="dhtmlxcalendar_line";this.contMonth.appendChild(g);var h=document.createElement("LI");h.className="dhtmlxcalendar_cell dhtmlxcalendar_month_hdr";h.innerHTML="<div class='dhtmlxcalendar_month_arrow dhtmlxcalendar_month_arrow_left' onmouseover='this.className=\"dhtmlxcalendar_month_arrow dhtmlxcalendar_month_arrow_left_hover\";' onmouseout='this.className=\"dhtmlxcalendar_month_arrow dhtmlxcalendar_month_arrow_left\";'></div><span class='dhtmlxcalendar_month_label_month'>Month</span><span class='dhtmlxcalendar_month_label_year'>Year</span><div class='dhtmlxcalendar_month_arrow dhtmlxcalendar_month_arrow_right' onmouseover='this.className=\"dhtmlxcalendar_month_arrow dhtmlxcalendar_month_arrow_right_hover\";' onmouseout='this.className=\"dhtmlxcalendar_month_arrow dhtmlxcalendar_month_arrow_right\";'></div>";
g.appendChild(h);var f=this;h.onclick=function(a){var a=a||event,b=a.target||a.srcElement;if(b.className&&b.className.indexOf("dhtmlxcalendar_month_arrow")===0){f._hideSelector();var c=b.parentNode.firstChild==b?-1:1;f._drawMonth(new Date(f._activeMonth.getFullYear(),f._activeMonth.getMonth()+c,1,0,0,0,0))}else b.className&&b.className=="dhtmlxcalendar_month_label_month"?(a.cancelBubble=!0,f._showSelector("month",31,21,"selector_month",!0)):b.className&&b.className=="dhtmlxcalendar_month_label_year"?
(a.cancelBubble=!0,f._showSelector("year",42,21,"selector_year",!0)):f._hideSelector()};this.contDays=document.createElement("DIV");this.contDays.className="dhtmlxcalendar_days_cont";this.base.appendChild(this.contDays);this.setWeekStartDay=function(a){a==0&&(a=7);this._wStart=Math.min(Math.max(isNaN(a)?1:a,1),7);this._drawDaysOfWeek()};this._drawDaysOfWeek=function(){if(this.contDays.childNodes.length==0){var a=document.createElement("UL");a.className="dhtmlxcalendar_line";this.contDays.appendChild(a)}else a=
this.contDays.firstChild;var b=this._wStart,c=this.langData[this.lang].daysSNames;c.push(String(this.langData[this.lang].daysSNames[0]).valueOf());for(var d=0;d<7;d++){if(a.childNodes[d]==null){var e=document.createElement("LI");a.appendChild(e)}else e=a.childNodes[d];e.className="dhtmlxcalendar_cell"+(b>=6?" dhtmlxcalendar_day_weekday_cell":"")+(d==0?"_first":"");e.innerHTML=c[b];++b>7&&(b=1)}this._activeMonth!=null&&this._drawMonth(this._activeMonth)};this._wStart=this.langData[this.lang].weekstart;
this.setWeekStartDay(this._wStart);this.contDates=document.createElement("DIV");this.contDates.className="dhtmlxcalendar_dates_cont";this.base.appendChild(this.contDates);this.contDates.onclick=function(a){var a=a||event,b=a.target||a.srcElement;if(b._date!=null&&!b._css_dis){var c=f._activeDate.getHours(),d=f._activeDate.getMinutes();if(!f.checkEvent("onBeforeChange")||f.callEvent("onBeforeChange",[new Date(b._date.getFullYear(),b._date.getMonth(),b._date.getDate(),c,d)])){if(f._activeDateCell!=
null)f._activeDateCell._css_date=!1,f._updateCellStyle(f._activeDateCell._q,f._activeDateCell._w);var e=f._hasParent&&f._activeDate.getFullYear()+"_"+f._activeDate.getMonth()!=b._date.getFullYear()+"_"+b._date.getMonth();f._activeDate=new Date(b._date.getFullYear(),b._date.getMonth(),b._date.getDate(),c,d);f._activeDateCell=b;f._activeDateCell._css_date=!0;f._activeDateCell._css_hover=!1;f._lastHover=null;f._updateCellStyle(f._activeDateCell._q,f._activeDateCell._w);e&&f._drawMonth(f._activeDate);
if(f._activeInp&&f.i[f._activeInp])f.i[f._activeInp].value=f._dateToStr(new Date(f._activeDate.getTime()));f._hasParent||f._hide();f.callEvent("onClick",[new Date(f._activeDate.getTime())])}}};this.contDates.onmouseover=function(a){var a=a||event,b=a.target||a.srcElement;if(b._date!=null)b._css_hover=!0,f._updateCellStyle(b._q,b._w),f._lastHover=b};this.contDates.onmouseout=function(){f._clearDayHover()};this._lastHover=null;this._clearDayHover=function(){if(this._lastHover)this._lastHover._css_hover=
!1,this._updateCellStyle(this._lastHover._q,this._lastHover._w),this._lastHover=null};for(e=0;e<6;e++){g=document.createElement("UL");g.className="dhtmlxcalendar_line";this.contDates.appendChild(g);for(var i=0;i<7;i++)h=document.createElement("LI"),h.className="dhtmlxcalendar_cell",g.appendChild(h)}this.contTime=document.createElement("DIV");this.contTime.className="dhtmlxcalendar_time_cont";this.base.appendChild(this.contTime);this.showTime=function(){if(String(this.base.className).search("dhtmlxcalendar_time_hidden")>
0)this.base.className=String(this.base.className).replace(/dhtmlxcalendar_time_hidden/gi,"")};this.hideTime=function(){String(this.base.className).search("dhtmlxcalendar_time_hidden")<0&&(this.base.className+=" dhtmlxcalendar_time_hidden")};g=document.createElement("UL");g.className="dhtmlxcalendar_line";this.contTime.appendChild(g);h=document.createElement("LI");h.className="dhtmlxcalendar_cell dhtmlxcalendar_time_hdr";h.innerHTML="<div class='dhtmlxcalendar_time_label'></div><span class='dhtmlxcalendar_label_hours'></span><span class='dhtmlxcalendar_label_colon'>:</span><span class='dhtmlxcalendar_label_minutes'></span>";
g.appendChild(h);h.onclick=function(a){var a=a||event,b=a.target||a.srcElement;b.className&&b.className=="dhtmlxcalendar_label_hours"?(a.cancelBubble=!0,f._showSelector("hours",3,115,"selector_hours",!0)):b.className&&b.className=="dhtmlxcalendar_label_minutes"?(a.cancelBubble=!0,f._showSelector("minutes",59,115,"selector_minutes",!0)):f._hideSelector()};this._activeMonth=null;this._activeDate=new Date;this._activeDateCell=null;this.setDate=function(a){a===""&&(a=new Date);a instanceof Date||(a=this._strToDate(a,
!1));var b=a.getTime();if(!this._isOutOfRange(b))this._activeDate=new Date(b),this._drawMonth(this._activeDate),this._updateVisibleHours(),this._updateVisibleMinutes()};this.getDate=function(a){var b=new Date(this._activeDate.getTime());return a?this._dateToStr(b):b};this._drawMonth=function(a){if(a instanceof Date){isNaN(a.getFullYear())&&(a=new Date(this._activeMonth.getFullYear(),this._activeMonth.getMonth(),1,0,0,0,0));this._activeMonth=new Date(a.getFullYear(),a.getMonth(),1,0,0,0,0);this._activeDateCell=
null;var b=new Date(this._activeMonth.getTime()),c=b.getDay(),d=c-this._wStart;d<0&&(d+=7);b.setDate(b.getDate()-d);for(var e=a.getMonth(),f=(new Date(this._activeDate.getFullYear(),this._activeDate.getMonth(),this._activeDate.getDate(),0,0,0,0)).getTime(),g=0,h=0;h<6;h++)for(var j=this._wStart,i=0;i<7;i++){var m=new Date(b.getFullYear(),b.getMonth(),b.getDate()+g++,0,0,0,0);this.contDates.childNodes[h].childNodes[i].innerHTML=m.getDate();var p=m.getDay(),l=m.getTime();this.contDates.childNodes[h].childNodes[i]._date=
new Date(l);this.contDates.childNodes[h].childNodes[i]._q=h;this.contDates.childNodes[h].childNodes[i]._w=i;this.contDates.childNodes[h].childNodes[i]._css_month=m.getMonth()==e;this.contDates.childNodes[h].childNodes[i]._css_date=l==f;this.contDates.childNodes[h].childNodes[i]._css_weekend=j>=6;this.contDates.childNodes[h].childNodes[i]._css_dis=this._isOutOfRange(l);this.contDates.childNodes[h].childNodes[i]._css_holiday=this._holidays[l]==!0;this._updateCellStyle(h,i);if(l==f)this._activeDateCell=
this.contDates.childNodes[h].childNodes[i];++j>7&&(j=1)}this.contMonth.firstChild.firstChild.childNodes[1].innerHTML=this.langData[this.lang].monthesFNames[a.getMonth()];this.contMonth.firstChild.firstChild.childNodes[2].innerHTML=a.getFullYear()}};this._updateCellStyle=function(a,b){var c=this.contDates.childNodes[a].childNodes[b],d="dhtmlxcalendar_cell dhtmlxcalendar_cell";d+=c._css_month?"_month":"";d+=c._css_date?"_date":"";d+=c._css_weekend?"_weekend":"";d+=c._css_holiday?"_holiday":"";d+=c._css_dis?
"_dis":"";d+=c._css_hover&&!c._css_dis?"_hover":"";c.className=d;c=null};this._initSelector=function(a,b){if(!this._selCover)this._selCover=document.createElement("DIV"),this._selCover.className="dhtmlxcalendar_selector_cover",this.base.appendChild(this._selCover);if(!this._sel)this._sel=document.createElement("DIV"),this._sel.className="dhtmlxcalendar_selector_obj",this.base.appendChild(this._sel),this._sel.appendChild(document.createElement("TABLE")),this._sel.firstChild.className="dhtmlxcalendar_selector_table",
this._sel.firstChild.cellSpacing=0,this._sel.firstChild.cellPadding=0,this._sel.firstChild.border=0,this._sel.firstChild.appendChild(document.createElement("TBODY")),this._sel.firstChild.firstChild.appendChild(document.createElement("TR")),this._sel.firstChild.firstChild.firstChild.appendChild(document.createElement("TD")),this._sel.firstChild.firstChild.firstChild.appendChild(document.createElement("TD")),this._sel.firstChild.firstChild.firstChild.appendChild(document.createElement("TD")),this._sel.firstChild.firstChild.firstChild.childNodes[0].className=
"dhtmlxcalendar_selector_cell_left",this._sel.firstChild.firstChild.firstChild.childNodes[1].className="dhtmlxcalendar_selector_cell_middle",this._sel.firstChild.firstChild.firstChild.childNodes[2].className="dhtmlxcalendar_selector_cell_right",this._sel.firstChild.firstChild.firstChild.childNodes[0].innerHTML="&nbsp;",this._sel.firstChild.firstChild.firstChild.childNodes[2].innerHTML="&nbsp;",this._sel.firstChild.firstChild.firstChild.childNodes[0].onmouseover=function(){this.className="dhtmlxcalendar_selector_cell_left dhtmlxcalendar_selector_cell_left_hover"},
this._sel.firstChild.firstChild.firstChild.childNodes[0].onmouseout=function(){this.className="dhtmlxcalendar_selector_cell_left"},this._sel.firstChild.firstChild.firstChild.childNodes[2].onmouseover=function(){this.className="dhtmlxcalendar_selector_cell_right dhtmlxcalendar_selector_cell_right_hover"},this._sel.firstChild.firstChild.firstChild.childNodes[2].onmouseout=function(){this.className="dhtmlxcalendar_selector_cell_right"},this._sel.firstChild.firstChild.firstChild.childNodes[0].onclick=
function(a){a=a||event;a.cancelBubble=!0;f._scrollYears(-1)},this._sel.firstChild.firstChild.firstChild.childNodes[2].onclick=function(a){a=a||event;a.cancelBubble=!0;f._scrollYears(1)},this._sel._ta={},this._selHover=null,this._sel.onmouseover=function(a){var a=a||event,b=a.target||a.srcElement;if(b._cell===!0&&(f._selHover!=b&&f._clearSelHover(),String(b.className).match(/^\s{0,}dhtmlxcalendar_selector_cell\s{0,}$/gi)!=null))b.className+=" dhtmlxcalendar_selector_cell_hover",f._selHover=b},this._sel.onmouseout=
function(){f._clearSelHover()},this._sel.appendChild(document.createElement("DIV")),this._sel.lastChild.className="dhtmlxcalendar_selector_obj_arrow";if(this._sel._ta[a]!=!0){if(a=="month"){this._msCells={};this.msCont=document.createElement("DIV");this.msCont.className="dhtmlxcalendar_area_"+b;this._sel.firstChild.firstChild.firstChild.childNodes[1].appendChild(this.msCont);for(var c=0,d=0;d<4;d++){var e=document.createElement("UL");e.className="dhtmlxcalendar_selector_line";this.msCont.appendChild(e);
for(var g=0;g<3;g++){var h=document.createElement("LI");h.innerHTML=this.langData[this.lang].monthesSNames[c];h.className="dhtmlxcalendar_selector_cell";e.appendChild(h);h._month=c;h._cell=!0;this._msCells[c++]=h}}this.msCont.onclick=function(a){a=a||event;a.cancelBubble=!0;var b=a.target||a.srcElement;b._month!=null&&(f._hideSelector(),f._updateActiveMonth(),f._drawMonth(new Date(f._activeMonth.getFullYear(),b._month,1,0,0,0,0)),f._doOnSelectorChange())}}if(a=="year"){this._ysCells={};this.ysCont=
document.createElement("DIV");this.ysCont.className="dhtmlxcalendar_area_"+b;this._sel.firstChild.firstChild.firstChild.childNodes[1].appendChild(this.ysCont);for(d=0;d<4;d++){e=document.createElement("UL");e.className="dhtmlxcalendar_selector_line";this.ysCont.appendChild(e);for(g=0;g<3;g++)h=document.createElement("LI"),h.className="dhtmlxcalendar_selector_cell",h._cell=!0,e.appendChild(h)}this.ysCont.onclick=function(a){a=a||event;a.cancelBubble=!0;var b=a.target||a.srcElement;b._year!=null&&(f._hideSelector(),
f._drawMonth(new Date(b._year,f._activeMonth.getMonth(),1,0,0,0,0)),f._doOnSelectorChange())}}if(a=="hours"){this._hsCells={};this.hsCont=document.createElement("DIV");this.hsCont.className="dhtmlxcalendar_area_"+b;this._sel.firstChild.firstChild.firstChild.childNodes[1].appendChild(this.hsCont);for(d=c=0;d<4;d++){e=document.createElement("UL");e.className="dhtmlxcalendar_selector_line";this.hsCont.appendChild(e);for(g=0;g<6;g++)h=document.createElement("LI"),h.innerHTML=this._fixLength(c,2),h.className=
"dhtmlxcalendar_selector_cell",e.appendChild(h),h._hours=c,h._cell=!0,this._hsCells[c++]=h}this.hsCont.onclick=function(a){a=a||event;a.cancelBubble=!0;var b=a.target||a.srcElement;b._hours!=null&&(f._hideSelector(),f._activeDate.setHours(b._hours),f._updateActiveHours(),f._updateVisibleHours(),f._doOnSelectorChange())}}if(a=="minutes"){this._rsCells={};this.rsCont=document.createElement("DIV");this.rsCont.className="dhtmlxcalendar_area_"+b;this._sel.firstChild.firstChild.firstChild.childNodes[1].appendChild(this.rsCont);
for(d=c=0;d<4;d++){e=document.createElement("UL");e.className="dhtmlxcalendar_selector_line";this.rsCont.appendChild(e);for(g=0;g<3;g++)h=document.createElement("LI"),h.innerHTML=this._fixLength(c,2),h.className="dhtmlxcalendar_selector_cell",e.appendChild(h),h._minutes=c,h._cell=!0,this._rsCells[c]=h,c+=5}this.rsCont.onclick=function(a){a=a||event;a.cancelBubble=!0;var b=a.target||a.srcElement;b._minutes!=null&&(f._hideSelector(),f._activeDate.setMinutes(b._minutes),f._updateActiveMinutes(),f._updateVisibleMinutes(),
f._doOnSelectorChange())}}this._sel._ta[a]=!0}};this._showSelector=function(a,b,c,d,e){e===!0&&this._sel!=null&&this._isSelectorVisible()&&a==this._sel._t?this._hideSelector():((!this._sel||!this._sel._ta[a])&&this._initSelector(a,d),this._selCover.style.display="",this._sel._t=a,this._sel.style.left=b+"px",this._sel.style.top=c+"px",this._sel.style.display="",this._sel.className="dhtmlxcalendar_selector_obj dhtmlxcalendar_"+d,this._doOnSelectorShow(a))};this._doOnSelectorShow=function(a){a=="month"&&
this._updateActiveMonth();a=="year"&&this._updateYearsList(this._activeMonth);a=="hours"&&this._updateActiveHours();a=="minutes"&&this._updateActiveMinutes()};this._hideSelector=function(){if(this._sel)this._sel.style.display="none",this._selCover.style.display="none"};this._isSelectorVisible=function(){return!this._sel?!1:this._sel.style.display!="none"};this._doOnSelectorChange=function(a){this.callEvent("onChange",[new Date(this._activeMonth.getFullYear(),this._activeMonth.getMonth(),this._activeDate.getDate(),
this._activeDate.getHours(),this._activeDate.getMinutes(),this._activeDate.getSeconds()),a])};this._clearSelHover=function(){if(this._selHover)this._selHover.className=String(this._selHover.className.replace(/dhtmlxcalendar_selector_cell_hover/gi,"")),this._selHover=null};this._updateActiveMonth=function(){if(typeof this._msActive!="undefined"&&typeof this._msCells[this._msActive]!="undefined")this._msCells[this._msActive].className="dhtmlxcalendar_selector_cell";this._msActive=this._activeMonth.getMonth();
this._msCells[this._msActive].className="dhtmlxcalendar_selector_cell dhtmlxcalendar_selector_cell_active"};this._updateActiveYear=function(){var a=this._activeMonth.getFullYear();if(this._ysCells[a])this._ysCells[a].className="dhtmlxcalendar_selector_cell dhtmlxcalendar_selector_cell_active"};this._updateYearsList=function(a){for(var b in this._ysCells)this._ysCells[b]=null,delete this._ysCells[b];for(var c=12*Math.floor(a.getFullYear()/12),d=0;d<4;d++)for(var e=0;e<3;e++)this.ysCont.childNodes[d].childNodes[e].innerHTML=
c,this.ysCont.childNodes[d].childNodes[e]._year=c,this.ysCont.childNodes[d].childNodes[e].className="dhtmlxcalendar_selector_cell",this._ysCells[c++]=this.ysCont.childNodes[d].childNodes[e];this._updateActiveYear()};this._scrollYears=function(a){var b=(a<0?this.ysCont.firstChild.firstChild._year:this.ysCont.lastChild.lastChild._year)+a,c=new Date(b,this._activeMonth.getMonth(),1,0,0,0,0);this._updateYearsList(c)};this._updateActiveHours=function(){if(typeof this._hsActive!="undefined"&&typeof this._hsCells[this._hsActive]!=
"undefined")this._hsCells[this._hsActive].className="dhtmlxcalendar_selector_cell";this._hsActive=this._activeDate.getHours();this._hsCells[this._hsActive].className="dhtmlxcalendar_selector_cell dhtmlxcalendar_selector_cell_active"};this._updateVisibleHours=function(){this.contTime.firstChild.firstChild.childNodes[1].innerHTML=this._fixLength(this._activeDate.getHours(),2)};this._updateActiveMinutes=function(){if(typeof this._rsActive!="undefined"&&typeof this._rsCells[this._rsActive]!="undefined")this._rsCells[this._rsActive].className=
"dhtmlxcalendar_selector_cell";this._rsActive=this._activeDate.getMinutes();if(typeof this._rsCells[this._rsActive]!="undefined")this._rsCells[this._rsActive].className="dhtmlxcalendar_selector_cell dhtmlxcalendar_selector_cell_active"};this._updateVisibleMinutes=function(){this.contTime.firstChild.firstChild.childNodes[3].innerHTML=this._fixLength(this._activeDate.getMinutes(),2)};this._fixLength=function(a,b){for(;String(a).length<b;)a="0"+String(a);return a};this._dateFormat="";this._dateFormatRE=
null;this.setDateFormat=function(a){this._dateFormat=a;this._dateFormatRE=RegExp(String(this._dateFormat).replace(/%[a-zA-Z]+/g,function(a){var b=a.replace(/%/,"");switch(b){case "m":case "d":case "H":case "i":case "s":return"\\d{2}";case "Y":return"\\d{4}"}return a}))};this.setDateFormat("%Y-%m-%d");this._strToDate=function(a,b,c){var d={Y:!1,m:!1,d:!1,H:!1,i:!1,s:!1},e=String(a).match(/[0-9]{1,}/g),f=(c||this._dateFormat).match(/%[a-zA-Z]/g);if(!e)return"Invalid Date";for(var g=0;g<f.length;g++){var h=
f[g].replace(/%/g,"");typeof d[h]!="undefined"&&(d[h]=Number(e[g]))}if(b)return d;for(e in d)d[e]===!1&&(d[e]=0);return new Date(d.Y,d.m-1,d.d,d.H,d.i,d.s,0)};this._dateToStr=function(a,b){if(a instanceof Date)var c=function(a){return String(a).length==1?"0"+String(a):a},d=function(b){switch(b){case "%d":return c(a.getDate());case "%j":return a.getDate();case "%D":return f.langData[f.lang].daysSNames[a.getDay()];case "%l":return f.langData[f.lang].daysFNames[a.getDay()];case "%m":return c(a.getMonth()+
1);case "%n":return date.getMonth()+1;case "%M":return f.langData[f.lang].monthesSNames[a.getMonth()];case "%F":return f.langData[f.lang].monthesFNames[a.getMonth()];case "%y":return c(a.getYear()%100);case "%Y":return a.getFullYear();case "%g":return(a.getHours()+11)%12+1;case "%h":return c((a.getHours()+11)%12+1);case "%G":return a.getHours();case "%H":return c(a.getHours());case "%i":return c(a.getMinutes());case "%s":return c(a.getSeconds());case "%a":return a.getHours()>11?"pm":"am";case "%A":return a.getHours()>
11?"PM":"AM";default:return b}},e=String(b||this._dateFormat).replace(/%[a-zA-Z]/g,d);return e||String(a)};this._updateDateStr=function(a){if(a=="")this.setDate(new Date),this.callEvent("onChange",[null,!0]);else if(this._dateFormatRE&&a.match(this._dateFormatRE)){var b=this._strToDate(a,!0),c=new Date(this._activeMonth.getFullYear(),this._activeMonth.getMonth(),this._activeDate.getDate(),this._activeDate.getHours(),this._activeDate.getMinutes(),this._activeDate.getSeconds());b.Y!==!1&&b.Y!=c.getFullYear()&&
this._activeDate.setFullYear(b.Y);b.m!==!1&&(b.m--,b.m!=c.getMonth()&&this._activeDate.setMonth(b.m));b.d!==!1&&b.d!=c.getDate()&&this._activeDate.setDate(b.d);b.H!==!1&&b.H!=c.getHours()&&this._activeDate.setHours(b.H);b.i!==!1&&b.i!=c.getMinutes()&&this._activeDate.setMinutes(b.i);b.s!==!1&&b.s!=c.getSeconds()&&this._activeDate.setSeconds(b.s);this._drawMonth(this._activeDate);this._updateVisibleMinutes();this._updateVisibleHours();this._sel&&this._isSelectorVisible()&&this._doOnSelectorShow(this._sel._t);
this._doOnSelectorChange(!0)}};this.setFormatedDate=function(a,b,c,d){var e=this._strToDate(b,!1,a);if(d)return e;this.setDate(e)};this.getFormatedDate=function(a,b){b&&b instanceof Date||(b=new Date(this._activeDate));return this._dateToStr(b,a)};this.show=function(a){if(!a&&this._hasParent)this._show();else if(typeof a=="object"&&typeof a._dhtmlxcalendar_uid!="undefined"&&this.i[a._dhtmlxcalendar_uid]==a)this._show(a._dhtmlxcalendar_uid);else{if(typeof a=="undefined")for(var b in this.i)a||(a=b);
a&&this._show(a)}};this.hide=function(){this._isVisible()&&this._hide()};this.draw=function(){this.show()};this.close=function(){this.hide()};this._activeInp=null;this.pos="bottom";this.setPosition=function(a,b){if(a=="right"||a=="bottom")this.pos=a;else if(!this._hasParent){if(typeof a!="undefined"&&!isNaN(a))this.base.style.left=a+"px";if(typeof b!="undefined"&&!isNaN(b))this.base.style.top=b+"px"}};this._show=function(a,b){b===!0&&this._activeInp==a&&this._isVisible()?this._hide():(a?(this.pos==
"right"?(this.base.style.left=this._getLeft(this.i[a])+this.i[a].offsetWidth-1+"px",this.base.style.top=this._getTop(this.i[a])+"px"):(this.base.style.left=this._getLeft(this.i[a])+"px",this.base.style.top=this._getTop(this.i[a])+this.i[a].offsetHeight-1+"px"),this._activeInp=a):(this.base.style.left="0px",this.base.style.top="0px"),this._hideSelector(),this.base.style.display="")};this._hide=function(){this._hideSelector();this.base.style.display="none";this._activeInp=null};this._isVisible=function(){return this.base.style.display!=
"none"};this._getLeft=function(a){return this._posGetOffset(a).left};this._getTop=function(a){return this._posGetOffset(a).top};this._posGetOffsetSum=function(a){for(var b=0,c=0;a;)b+=parseInt(a.offsetTop),c+=parseInt(a.offsetLeft),a=a.offsetParent;return{top:b,left:c}};this._posGetOffsetRect=function(a){var b=a.getBoundingClientRect(),c=document.body,d=document.documentElement,e=window.pageYOffset||d.scrollTop||c.scrollTop,f=window.pageXOffset||d.scrollLeft||c.scrollLeft,g=d.clientTop||c.clientTop||
0,h=d.clientLeft||c.clientLeft||0,j=b.top+e-g,i=b.left+f-h;return{top:Math.round(j),left:Math.round(i)}};this._posGetOffset=function(a){return this[a.getBoundingClientRect?"_posGetOffsetRect":"_posGetOffsetSum"](a)};this._rangeActive=!1;this._rangeTo=this._rangeFrom=null;this._rangeSet={};this.setInsensitiveDays=function(a){for(var b=this._extractDates(a),c=0;c<b.length;c++)this._rangeSet[(new Date(b[c].getFullYear(),b[c].getMonth(),b[c].getDate(),0,0,0,0)).getTime()]=!0;this._drawMonth(this._activeDate)};
this.clearInsensitiveDays=function(){this._clearRangeSet();this._drawMonth(this._activeDate)};this._holidays={};this.setHolidays=function(a){if(a==null)this._clearHolidays();else if(a!=null)for(var b=this._extractDates(a),c=0;c<b.length;c++)this._holidays[(new Date(b[c].getFullYear(),b[c].getMonth(),b[c].getDate(),0,0,0,0)).getTime()]=!0;this._drawMonth(this._activeDate)};this._extractDates=function(a){if(typeof a=="string"||a instanceof Date)a=[a];for(var b=[],c=0;c<a.length;c++)if(typeof a[c]==
"string")for(var d=a[c].split(","),e=0;e<d.length;e++)b.push(this._strToDate(d[e],!1));else a[c]instanceof Date&&b.push(a[c]);return b};this._clearRange=function(){this._rangeActive=!1;this._rangeTo=this._rangeFrom=this._rangeType=null};this._clearRangeSet=function(){for(var a in this._rangeSet)this._rangeSet[a]=null,delete this._rangeSet[a]};this._clearHolidays=function(){for(var a in this._holidays)this._holidays[a]=null,delete this._holidays[a]};this._isOutOfRange=function(a){if(this._rangeSet[a]==
!0)return!0;if(this._rangeActive){if(this._rangeType=="in"&&(a<this._rangeFrom||a>this._rangeTo))return!0;if(this._rangeType=="out"&&a>=this._rangeFrom&&a<=this._rangeTo)return!0;if(this._rangeType=="from"&&a<this._rangeFrom)return!0;if(this._rangeType=="to"&&a>this._rangeTo)return!0}return!1};this.clearSensitiveRange=function(){this._clearRange();this._drawMonth(this._activeDate)};this.setSensitiveRange=function(a,b,c){var d=!1;if(a!=null&&b!=null){a instanceof Date||(a=this._strToDate(a,!1));b instanceof
Date||(b=this._strToDate(b,!1));if(a.getTime()>b.getTime())return;this._rangeFrom=(new Date(a.getFullYear(),a.getMonth(),a.getDate(),0,0,0,0)).getTime();this._rangeTo=(new Date(b.getFullYear(),b.getMonth(),b.getDate(),0,0,0,0)).getTime();this._rangeActive=!0;this._rangeType="in";d=!0}if(!d&&a!=null&&b==null)a instanceof Date||(a=this._strToDate(a,!1)),this._rangeFrom=(new Date(a.getFullYear(),a.getMonth(),a.getDate(),0,0,0,0)).getTime(),this._rangeTo=null,c===!0&&this._rangeFrom++,this._rangeActive=
!0,this._rangeType="from",d=!0;if(!d&&a==null&&b!=null)b instanceof Date||(b=this._strToDate(b,!1)),this._rangeFrom=null,this._rangeTo=(new Date(b.getFullYear(),b.getMonth(),b.getDate(),0,0,0,0)).getTime(),c===!0&&this._rangeTo--,this._rangeActive=!0,this._rangeType="to",d=!0;d&&this._drawMonth(this._activeDate)};this.setInsensitiveRange=function(a,b){if(a!=null&&b!=null){if(a instanceof Date||(a=this._strToDate(a,!1)),b instanceof Date||(b=this._strToDate(b,!1)),!(a.getTime()>b.getTime()))this._rangeFrom=
(new Date(a.getFullYear(),a.getMonth(),a.getDate(),0,0,0,0)).getTime(),this._rangeTo=(new Date(b.getFullYear(),b.getMonth(),b.getDate(),0,0,0,0)).getTime(),this._rangeActive=!0,this._rangeType="out",this._drawMonth(this._activeDate)}else a!=null&&b==null?this.setSensitiveRange(null,a,!0):a==null&&b!=null&&this.setSensitiveRange(b,null,!0)};this._doOnClick=function(a){var a=a||event,b=a.target||a.srcElement;if(b._dhtmlxcalendar_uid&&b._dhtmlxcalendar_uid!=f._activeInp&&f._isVisible())f._hide();else if(!b._dhtmlxcalendar_uid||
!f.i[b._dhtmlxcalendar_uid])f._isSelectorVisible()?f._hideSelector():!f._hasParent&&f._isVisible()&&f._hide()};this._doOnKeyDown=function(a){a=a||event;a.keyCode==27&&(f._isSelectorVisible()?f._hideSelector():f._isVisible()&&!f._hasParent&&f._hide())};this._doOnInpClick=function(a){var a=a||event,b=a.target||a.srcElement;b._dhtmlxcalendar_uid&&(f._updateDateStr(b.value),f._show(b._dhtmlxcalendar_uid,!0))};this._doOnInpKeyUp=function(a){var a=a||event,b=a.target||a.srcElement;a.keyCode!=13&&b._dhtmlxcalendar_uid&&
f._updateDateStr(b.value)};this._doOnUnload=function(){f.unload()};window.addEventListener?(document.body.addEventListener("click",f._doOnClick,!1),window.addEventListener("keydown",f._doOnKeyDown,!1),window.addEventListener("unload",f._doOnUnload,!1)):(document.body.attachEvent("onclick",f._doOnClick),document.body.attachEvent("onkeydown",f._doOnKeyDown),window.attachEvent("onunload",f._doOnUnload));this.attachObj=function(a){var b=this.uid();this.i[b]=a;this._attachEventsToObject(b)};this.detachObj=
function(a){var b=a._dhtmlxcalendar_uid;if(this.i[b]!=null)this._detachEventsFromObject(b),this.i[b]._dhtmlxcalendar_uid=null,this.i[b]=null,delete this.i[b]};this._attachEventsToObject=function(a){this.i[a]._dhtmlxcalendar_uid=a;window.addEventListener?(this.i[a].addEventListener("click",f._doOnInpClick,!1),this.i[a].addEventListener("keyup",f._doOnInpKeyUp,!1)):(this.i[a].attachEvent("onclick",f._doOnInpClick),this.i[a].attachEvent("onkeyup",f._doOnInpKeyUp))};this._detachEventsFromObject=function(a){window.addEventListener?
(this.i[a].removeEventListener("click",f._doOnInpClick,!1),this.i[a].removeEventListener("keyup",f._doOnInpKeyUp,!1)):(this.i[a].detachEvent("onclick",f._doOnInpClick),this.i[a].detachEvent("onkeyup",f._doOnInpKeyUp))};for(var j in this.i)this._attachEventsToObject(j);this.evs={};this.attachEvent=function(a,b){var c=this.uid();this.evs[c]={name:String(a).toLowerCase(),func:b};return c};this.detachEvent=function(a){if(this.evs[a])this.evs[a].name=null,this.evs[a].func=null,this.evs[a]=null,delete this.evs[a]};
this.callEvent=function(a,b){var c=!0,d=String(a).toLowerCase(),b=b||[],e;for(e in this.evs)if(this.evs[e].name==d)var f=this.evs[e].func.apply(this,b),c=c&&f;return c};this.checkEvent=function(a){var b=!1,c=String(a).toLowerCase(),d;for(d in this.evs)b=b||this.evs[d].name==c;return b};this.unload=function(){this.uidd=this.uid=this._lastHover=this._dateFormatRE=this._dateFormat=this._activeMonth=this._activeInp=this._activeDateCell=this._activeDate=null;window.addEventListener?(document.body.removeEventListener("click",
f._doOnClick,!1),window.removeEventListener("keydown",f._doOnKeyDown,!1),window.removeEventListener("unload",f._doOnUnload,!1)):(document.body.detachEvent("onclick",f._doOnClick),document.body.detachEvent("onkeydown",f._doOnKeyDown),window.detachEvent("onunload",f._doOnKeyDown));this._doOnUnload=this._doOnKeyDown=this._doOnClick=null;for(var a in this.i)this.i[a]._dhtmlxcalendar_uid=null,delete this.i[a]._dhtmlxcalendar_uid,window.addEventListener?(this.i[a].removeEventListener("click",f._doOnInpClick,
!1),this.i[a].removeEventListener("keyup",f._doOnInpKeyUp,!1)):(this.i[a].detachEvent("onclick",f._doOnInpClick),this.i[a].detachEvent("onkeyup",f._doOnInpKeyUp)),this.i[a]=null,delete this.i[a];this._doOnInpKeyUp=this._doOnInpClick=this.i=null;for(a in this.evs)this.detachEvent(a);this.callEvent=this.checkEvent=this.detachEvent=this.attachEvent=this.evs=null;this.contMonth.onselectstart=null;this.contMonth.firstChild.firstChild.onclick=null;this.contMonth.firstChild.firstChild.firstChild.onmouseover=
null;this.contMonth.firstChild.firstChild.firstChild.onmouseout=null;this.contMonth.firstChild.firstChild.lastChild.onmouseover=null;for(this.contMonth.firstChild.firstChild.lastChild.onmouseout=null;this.contMonth.firstChild.firstChild.childNodes.length>0;)this.contMonth.firstChild.firstChild.removeChild(this.contMonth.firstChild.firstChild.lastChild);this.contMonth.firstChild.removeChild(this.contMonth.firstChild.firstChild);this.contMonth.removeChild(this.contMonth.firstChild);this.contMonth.parentNode.removeChild(this.contMonth);
for(this.contMonth=null;this.contDays.firstChild.childNodes.length>0;)this.contDays.firstChild.removeChild(this.contDays.firstChild.lastChild);this.contDays.removeChild(this.contDays.firstChild);this.contDays.parentNode.removeChild(this.contDays);this.contDays=null;this.contDates.onclick=null;this.contDates.onmouseover=null;for(this.contDates.onmouseout=null;this.contDates.childNodes.length>0;){for(;this.contDates.lastChild.childNodes.length>0;)this.contDates.lastChild.lastChild._css_date=null,this.contDates.lastChild.lastChild._css_month=
null,this.contDates.lastChild.lastChild._css_weekend=null,this.contDates.lastChild.lastChild._css_hover=null,this.contDates.lastChild.lastChild._date=null,this.contDates.lastChild.lastChild._q=null,this.contDates.lastChild.lastChild._w=null,this.contDates.lastChild.removeChild(this.contDates.lastChild.lastChild);this.contDates.removeChild(this.contDates.lastChild)}this.contDates.parentNode.removeChild(this.contDates);this.contDates=null;for(this.contTime.firstChild.firstChild.onclick=null;this.contTime.firstChild.firstChild.childNodes.length>
0;)this.contTime.firstChild.firstChild.removeChild(this.contTime.firstChild.firstChild.lastChild);this.contTime.firstChild.removeChild(this.contTime.firstChild.firstChild);this.contTime.removeChild(this.contTime.firstChild);this.contTime.parentNode.removeChild(this.contTime);this._lastHover=this.contTime=null;if(this.msCont){this._msActive=this.msCont.onclick=null;for(a in this._msCells)this._msCells[a]._cell=null,this._msCells[a]._month=null,this._msCells[a].parentNode.removeChild(this._msCells[a]),
this._msCells[a]=null;for(this._msCells=null;this.msCont.childNodes.length>0;)this.msCont.removeChild(this.msCont.lastChild);this.msCont.parentNode.removeChild(this.msCont);this.msCont=null}if(this.ysCont){this.ysCont.onclick=null;for(a in this._ysCells)this._ysCells[a]._cell=null,this._ysCells[a]._year=null,this._ysCells[a].parentNode.removeChild(this._ysCells[a]),this._ysCells[a]=null;for(this._ysCells=null;this.ysCont.childNodes.length>0;)this.ysCont.removeChild(this.ysCont.lastChild);this.ysCont.parentNode.removeChild(this.ysCont);
this.ysCont=null}if(this.hsCont){this._hsActive=this.hsCont.onclick=null;for(a in this._hsCells)this._hsCells[a]._cell=null,this._hsCells[a]._hours=null,this._hsCells[a].parentNode.removeChild(this._hsCells[a]),this._hsCells[a]=null;for(this._hsCells=null;this.hsCont.childNodes.length>0;)this.hsCont.removeChild(this.hsCont.lastChild);this.hsCont.parentNode.removeChild(this.hsCont);this.hsCont=null}if(this.rsCont){this._rsActive=this.rsCont.onclick=null;for(a in this._rsCells)this._rsCells[a]._cell=
null,this._rsCells[a]._minutes=null,this._rsCells[a].parentNode.removeChild(this._rsCells[a]),this._rsCells[a]=null;for(this._rsCells=null;this.rsCont.childNodes.length>0;)this.rsCont.removeChild(this.rsCont.lastChild);this.rsCont.parentNode.removeChild(this.rsCont);this.rsCont=null}if(this._selCover)this._selCover.parentNode.removeChild(this._selCover),this._selCover=null;if(this._sel){for(a in this._sel._ta)this._sel._ta[a]=null;this._sel._ta=null;this._sel._t=null;this._sel.onmouseover=null;for(this._sel.onmouseout=
null;this._sel.firstChild.firstChild.firstChild.childNodes.length>0;)this._sel.firstChild.firstChild.firstChild.lastChild.onclick=null,this._sel.firstChild.firstChild.firstChild.lastChild.onmouseover=null,this._sel.firstChild.firstChild.firstChild.lastChild.onmouseout=null,this._sel.firstChild.firstChild.firstChild.removeChild(this._sel.firstChild.firstChild.firstChild.lastChild);this._sel.firstChild.firstChild.removeChild(this._sel.firstChild.firstChild.firstChild);for(this._sel.firstChild.removeChild(this._sel.firstChild.firstChild);this._sel.childNodes.length>
0;)this._sel.removeChild(this._sel.lastChild);this._sel.parentNode.removeChild(this._sel);this._sel=null}this.base.onclick=null;this.base.parentNode.removeChild(this.base);this.unload=this.showTime=this.show=this.setDateFormat=this.setDate=this.hideTime=this.hide=this._updateYearsList=this._updateVisibleMinutes=this._updateVisibleHours=this._updateDateStr=this._updateCellStyle=this._updateActiveYear=this._updateActiveMonth=this._updateActiveMinutes=this._updateActiveHours=this._strToDate=this._showSelector=
this._show=this._scrollYears=this._posGetOffsetSum=this._posGetOffsetRect=this._posGetOffset=this._isVisible=this._isSelectorVisible=this._initSelector=this._hideSelector=this._hide=this._getTop=this._getLeft=this._fixLength=this._drawMonth=this._doOnSelectorShow=this._doOnSelectorChange=this._clearSelHover=this._clearDayHover=this.base=null;for(a in this)delete this[a];a=f=null};this.setDate(this._activeDate);return this}dhtmlXCalendarObject.prototype.setYearsRange=function(){};
dhtmlXCalendarObject.prototype.lang="en";dhtmlXCalendarObject.prototype.langData={en:{dateformat:"%Y-%m-%d",monthesFNames:"January,February,March,April,May,June,July,August,September,October,November,December".split(","),monthesSNames:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(","),daysFNames:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),daysSNames:"Su,Mo,Tu,We,Th,Fr,Sa".split(","),weekstart:1}};dhtmlxCalendarObject=dhtmlXCalendarObject;
function dataProcessor(a){this.serverProcessor=a;this.action_param="!nativeeditor_status";this.object=null;this.updatedRows=[];this.autoUpdate=!0;this.updateMode="cell";this._tMode="GET";this.post_delim="_";this._waitMode=0;this._in_progress={};this._invalid={};this.mandatoryFields=[];this.messages=[];this.styles={updated:"font-weight:bold;",inserted:"font-weight:bold;",deleted:"text-decoration : line-through;",invalid:"background-color:FFE0E0;",invalid_cell:"border-bottom:2px solid red;",clear:"font-weight:normal;text-decoration:none;"};
this.enableUTFencoding(!0);dhtmlxEventable(this);return this}
dataProcessor.prototype={setTransactionMode:function(a,b){this._tMode=a;this._tSend=b},escape:function(a){return this._utf?encodeURIComponent(a):escape(a)},enableUTFencoding:function(a){this._utf=convertStringToBoolean(a)},setDataColumns:function(a){this._columns=typeof a=="string"?a.split(","):a},getSyncState:function(){return!this.updatedRows.length},enableDataNames:function(a){this._endnm=convertStringToBoolean(a)},enablePartialDataSend:function(a){this._changed=convertStringToBoolean(a)},setUpdateMode:function(a,
b){this.autoUpdate=a=="cell";this.updateMode=a;this.dnd=b},ignore:function(a,b){this._silent_mode=!0;a.call(b||window);this._silent_mode=!1},setUpdated:function(a,b,c){if(!this._silent_mode){var d=this.findRow(a),c=c||"updated",e=this.obj.getUserData(a,this.action_param);e&&c=="updated"&&(c=e);b?(this.set_invalid(a,!1),this.updatedRows[d]=a,this.obj.setUserData(a,this.action_param,c),this._in_progress[a]&&(this._in_progress[a]="wait")):this.is_invalid(a)||(this.updatedRows.splice(d,1),this.obj.setUserData(a,
this.action_param,""));b||this._clearUpdateFlag(a);this.markRow(a,b,c);b&&this.autoUpdate&&this.sendData(a)}},_clearUpdateFlag:function(){},markRow:function(a,b,c){var d="",e=this.is_invalid(a);e&&(d=this.styles[e],b=!0);if(this.callEvent("onRowMark",[a,b,c,e])&&(d=this.styles[b?c:"clear"]+d,this.obj[this._methods[0]](a,d),e&&e.details)){d+=this.styles[e+"_cell"];for(var g=0;g<e.details.length;g++)if(e.details[g])this.obj[this._methods[1]](a,g,d)}},getState:function(a){return this.obj.getUserData(a,
this.action_param)},is_invalid:function(a){return this._invalid[a]},set_invalid:function(a,b,c){c&&(b={value:b,details:c,toString:function(){return this.value.toString()}});this._invalid[a]=b},checkBeforeUpdate:function(){return!0},sendData:function(a){if(!this._waitMode||!(this.obj.mytype=="tree"||this.obj._h2)){this.obj.editStop&&this.obj.editStop();if(typeof a=="undefined"||this._tSend)return this.sendAllData();if(this._in_progress[a])return!1;this.messages=[];if(!this.checkBeforeUpdate(a)&&this.callEvent("onValidationError",
[a,this.messages]))return!1;this._beforeSendData(this._getRowData(a),a)}},_beforeSendData:function(a,b){if(!this.callEvent("onBeforeUpdate",[b,this.getState(b),a]))return!1;this._sendData(a,b)},serialize:function(a,b){if(typeof a=="string")return a;if(typeof b!="undefined")return this.serialize_one(a,"");else{var c=[],d=[],e;for(e in a)a.hasOwnProperty(e)&&(c.push(this.serialize_one(a[e],e+this.post_delim)),d.push(e));c.push("ids="+this.escape(d.join(",")));return c.join("&")}},serialize_one:function(a,
b){if(typeof a=="string")return a;var c=[],d;for(d in a)a.hasOwnProperty(d)&&c.push(this.escape((b||"")+d)+"="+this.escape(a[d]));return c.join("&")},_sendData:function(a,b){if(a){if(!this.callEvent("onBeforeDataSending",b?[b,this.getState(b),a]:[null,null,a]))return!1;b&&(this._in_progress[b]=(new Date).valueOf());var c=new dtmlXMLLoaderObject(this.afterUpdate,this,!0),d=this.serverProcessor+(this._user?getUrlSymbol(this.serverProcessor)+["dhx_user="+this._user,"dhx_version="+this.obj.getUserData(0,
"version")].join("&"):"");this._tMode!="POST"?c.loadXML(d+(d.indexOf("?")!=-1?"&":"?")+this.serialize(a,b)):c.loadXML(d,!0,this.serialize(a,b));this._waitMode++}},sendAllData:function(){if(this.updatedRows.length){this.messages=[];for(var a=!0,b=0;b<this.updatedRows.length;b++)a&=this.checkBeforeUpdate(this.updatedRows[b]);if(!a&&!this.callEvent("onValidationError",["",this.messages]))return!1;if(this._tSend)this._sendData(this._getAllData());else for(b=0;b<this.updatedRows.length;b++)if(!this._in_progress[this.updatedRows[b]]&&
!this.is_invalid(this.updatedRows[b])&&(this._beforeSendData(this._getRowData(this.updatedRows[b]),this.updatedRows[b]),this._waitMode&&(this.obj.mytype=="tree"||this.obj._h2)))break}},_getAllData:function(){for(var a={},b=!1,c=0;c<this.updatedRows.length;c++){var d=this.updatedRows[c];!this._in_progress[d]&&!this.is_invalid(d)&&this.callEvent("onBeforeUpdate",[d,this.getState(d)])&&(a[d]=this._getRowData(d,d+this.post_delim),b=!0,this._in_progress[d]=(new Date).valueOf())}return b?a:null},setVerificator:function(a,
b){this.mandatoryFields[a]=b||function(a){return a!=""}},clearVerificator:function(a){this.mandatoryFields[a]=!1},findRow:function(a){for(var b=0,b=0;b<this.updatedRows.length;b++)if(a==this.updatedRows[b])break;return b},defineAction:function(a,b){if(!this._uActions)this._uActions=[];this._uActions[a]=b},afterUpdateCallback:function(a,b,c,d){var e=a,g=c!="error"&&c!="invalid";g||this.set_invalid(a,c);if(this._uActions&&this._uActions[c]&&!this._uActions[c](d))return delete this._in_progress[e];this._in_progress[e]!=
"wait"&&this.setUpdated(a,!1);var h=a;switch(c){case "inserted":case "insert":b!=a&&(this.obj[this._methods[2]](a,b),a=b);break;case "delete":case "deleted":return this.obj.setUserData(a,this.action_param,"true_deleted"),this.obj[this._methods[3]](a),delete this._in_progress[e],this.callEvent("onAfterUpdate",[a,c,b,d])}this._in_progress[e]!="wait"?(g&&this.obj.setUserData(a,this.action_param,""),delete this._in_progress[e]):(delete this._in_progress[e],this.setUpdated(b,!0,this.obj.getUserData(a,
this.action_param)));this.callEvent("onAfterUpdate",[a,c,b,d])},afterUpdate:function(a,b,c,d,e){e.getXMLTopNode("data");if(e.xmlDoc.responseXML){for(var g=e.doXPath("//data/action"),h=0;h<g.length;h++){var f=g[h],i=f.getAttribute("type"),j=f.getAttribute("sid"),o=f.getAttribute("tid");a.afterUpdateCallback(j,o,i,f)}a.finalizeUpdate()}},finalizeUpdate:function(){this._waitMode&&this._waitMode--;(this.obj.mytype=="tree"||this.obj._h2)&&this.updatedRows.length&&this.sendData();this.callEvent("onAfterUpdateFinish",
[]);this.updatedRows.length||this.callEvent("onFullSync",[])},init:function(a){this.obj=a;this.obj._dp_init&&this.obj._dp_init(this)},setOnAfterUpdate:function(a){this.attachEvent("onAfterUpdate",a)},enableDebug:function(){},setOnBeforeUpdateHandler:function(a){this.attachEvent("onBeforeDataSending",a)},setAutoUpdate:function(a,b){a=a||2E3;this._user=b||(new Date).valueOf();this._need_update=!1;this._loader=null;this._update_busy=!1;this.attachEvent("onAfterUpdate",function(a,b,c,h){this.afterAutoUpdate(a,
b,c,h)});this.attachEvent("onFullSync",function(){this.fullSync()});var c=this;window.setInterval(function(){c.loadUpdate()},a)},afterAutoUpdate:function(a,b){return b=="collision"?(this._need_update=!0,!1):!0},fullSync:function(){if(this._need_update==!0)this._need_update=!1,this.loadUpdate();return!0},getUpdates:function(a,b){if(this._update_busy)return!1;else this._update_busy=!0;this._loader=this._loader||new dtmlXMLLoaderObject(!0);this._loader.async=!0;this._loader.waitCall=b;this._loader.loadXML(a)},
_v:function(a){return a.firstChild?a.firstChild.nodeValue:""},_a:function(a){for(var b=[],c=0;c<a.length;c++)b[c]=this._v(a[c]);return b},loadUpdate:function(){var a=this,b=this.obj.getUserData(0,"version"),c=this.serverProcessor+getUrlSymbol(this.serverProcessor)+["dhx_user="+this._user,"dhx_version="+b].join("&"),c=c.replace("editing=true&","");this.getUpdates(c,function(){var b=a._loader.doXPath("//userdata");a.obj.setUserData(0,"version",a._v(b[0]));var c=a._loader.doXPath("//update");if(c.length){a._silent_mode=
!0;for(var g=0;g<c.length;g++){var h=c[g].getAttribute("status"),f=c[g].getAttribute("id"),i=c[g].getAttribute("parent");switch(h){case "inserted":a.callEvent("insertCallback",[c[g],f,i]);break;case "updated":a.callEvent("updateCallback",[c[g],f,i]);break;case "deleted":a.callEvent("deleteCallback",[c[g],f,i])}}a._silent_mode=!1}a._update_busy=!1;a=null})}};window.dhx||(dhx={});dhx.version="3.0";dhx.codebase="./";dhx.name="Core";dhx.copy=function(a){var b=dhx.copy.W;b.prototype=a;return new b};
dhx.copy.W=function(){};dhx.extend=function(a,b,c){a.r&&(a=a.r[0]);for(var d in b)if(!a[d]||c)a[d]=b[d];b.defaults&&dhx.extend(a.defaults,b.defaults);b.c&&b.c.call(a);return a};dhx.fullCopy=function(a){var b=a.length?[]:{};arguments.length>1&&(b=arguments[0],a=arguments[1]);for(var c in a)typeof a[c]=="object"?(b[c]=a[c].length?[]:{},dhx.fullCopy(b[c],a[c])):b[c]=a[c];return b};dhx.single=function(a){var b=null,c=function(){b||(b=new a({}));b.ba&&b.ba.apply(b,arguments);return b};return c};
dhx.protoUI=function(){var a=arguments,b=a[0].name,c=function(d){if(a){for(var e=[a[0]],g=1;g<a.length;g++)e[g]=a[g],e[g].r&&(e[g]=e[g].call(dhx)),e[g].prototype&&e[g].prototype.name&&(dhx.ui[e[g].prototype.name]=e[g]);dhx.ui[b]=dhx.proto.apply(dhx,e);if(c.m)for(g=0;g<c.m.length;g++)dhx.Type(dhx.ui[b],c.m[g]);c=a=null}return this!=dhx?new dhx.ui[b](d):dhx.ui[b]};c.r=arguments;return dhx.ui[b]=c};
dhx.proto=function(){for(var a=arguments,b=a[0],c=!!b.c,d=[],e=a.length-1;e>0;e--){if(typeof a[e]=="function")a[e]=a[e].prototype;a[e].c&&d.push(a[e].c);if(a[e].defaults){var g=a[e].defaults;if(!b.defaults)b.defaults={};for(var h in g)dhx.isNotDefined(b.defaults[h])&&(b.defaults[h]=g[h])}if(a[e].type&&b.type)for(h in a[e].type)b.type[h]||(b.type[h]=a[e].type[h]);for(var f in a[e])b[f]||(b[f]=a[e][f])}c&&d.push(b.c);b.c=function(){for(var a=0;a<d.length;a++)d[a].apply(this,arguments)};var i=function(a){this.w=
[];this.c(a);this.O&&this.O(a,this.defaults);for(a=0;a<this.w.length;a++)this.w[a].call(this)};i.prototype=b;b=a=null;return i};dhx.bind=function(a,b){return function(){return a.apply(b,arguments)}};dhx.require=function(a){dhx.L[a]||(dhx.exec(dhx.ajax().sync().get(dhx.codebase+a).responseText),dhx.L[a]=!0)};dhx.L={};dhx.exec=function(a){window.execScript?window.execScript(a):window.eval(a)};dhx.wrap=function(a,b){return!a?b:function(){var c=a.apply(this,arguments);b.apply(this,arguments);return c}};
dhx.methodPush=function(a,b){return function(){var c=!1;return c=a[b].apply(a,arguments)}};dhx.isNotDefined=function(a){return typeof a=="undefined"};dhx.delay=function(a,b,c,d){return window.setTimeout(function(){var d=a.apply(b,c||[]);a=b=c=null;return d},d||1)};dhx.uid=function(){if(!this.G)this.G=(new Date).valueOf();this.G++;return this.G};dhx.toNode=function(a){return typeof a=="string"?document.getElementById(a):a};dhx.toArray=function(a){return dhx.extend(a||[],dhx.PowerArray,!0)};
dhx.toFunctor=function(a){return typeof a=="string"?eval(a):a};dhx.g={};dhx.event=function(a,b,c,d){var a=dhx.toNode(a),e=dhx.uid();d&&(c=dhx.bind(c,d));dhx.g[e]=[a,b,c];a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c);return e};dhx.eventRemove=function(a){if(a){var b=dhx.g[a];b[0].removeEventListener?b[0].removeEventListener(b[1],b[2],!1):b[0].detachEvent&&b[0].detachEvent("on"+b[1],b[2]);delete this.g[a]}};
dhx.EventSystem={c:function(){this.g={};this.n={};this.C={}},blockEvent:function(){this.g.I=!0},unblockEvent:function(){this.g.I=!1},mapEvent:function(a){dhx.extend(this.C,a,!0)},callEvent:function(a,b){if(this.g.I)return!0;var a=a.toLowerCase(),c=this.g[a.toLowerCase()],d=!0;if(c)for(var e=0;e<c.length;e++)if(c[e].apply(this,b||[])===!1)d=!1;this.C[a]&&!this.C[a].callEvent(a,b)&&(d=!1);return d},attachEvent:function(a,b,c){var a=a.toLowerCase(),c=c||dhx.uid(),b=dhx.toFunctor(b),d=this.g[a]||dhx.toArray();
d.push(b);this.g[a]=d;this.n[c]={f:b,t:a};return c},detachEvent:function(a){if(this.n[a]){var b=this.n[a].t,c=this.n[a].f,b=this.g[b];b.remove(c);delete this.n[a]}},hasEvent:function(a){a=a.toLowerCase();return this.g[a]?!0:!1}};dhx.extend(dhx,dhx.EventSystem);
dhx.PowerArray={removeAt:function(a,b){a>=0&&this.splice(a,b||1)},remove:function(a){this.removeAt(this.find(a))},insertAt:function(a,b){if(!b&&b!==0)this.push(a);else{var c=this.splice(b,this.length-b);this[b]=a;this.push.apply(this,c)}},find:function(a){for(var b=0;b<this.length;b++)if(a==this[b])return b;return-1},each:function(a,b){for(var c=0;c<this.length;c++)a.call(b||this,this[c])},map:function(a,b){for(var c=0;c<this.length;c++)this[c]=a.call(b||this,this[c]);return this}};dhx.env={};
(function(){if(navigator.userAgent.indexOf("Mobile")!=-1)dhx.env.mobile=!0;if(dhx.env.mobile||navigator.userAgent.indexOf("iPad")!=-1||navigator.userAgent.indexOf("Android")!=-1)dhx.env.touch=!0;navigator.userAgent.indexOf("Opera")!=-1?dhx.env.isOpera=!0:(dhx.env.isIE=!!document.all,dhx.env.isFF=!document.all,dhx.env.isWebKit=navigator.userAgent.indexOf("KHTML")!=-1,dhx.env.isSafari=dhx.env.isWebKit&&navigator.userAgent.indexOf("Mac")!=-1);if(navigator.userAgent.toLowerCase().indexOf("android")!=
-1)dhx.env.isAndroid=!0;dhx.env.transform=!1;dhx.env.transition=!1;for(var a={names:["transform","transition"],transform:["transform","WebkitTransform","MozTransform","oTransform","msTransform"],transition:["transition","WebkitTransition","MozTransition","oTransition","msTransition"]},b=document.createElement("DIV"),c=0;c<a.names.length;c++)for(var d=a[a.names[c]],e=0;e<d.length;e++)if(typeof b.style[d[e]]!="undefined"){dhx.env[a.names[c]]=d[e];break}b.style[dhx.env.transform]="translate3d(0,0,0)";
dhx.env.translate=b.style[dhx.env.transform]?"translate3d":"translate";dhx.env.transformCSSPrefix=function(){var a;dhx.env.isOpera?a="-o-":(a="",dhx.env.isFF&&(a="-Moz-"),dhx.env.isWebKit&&(a="-webkit-"),dhx.env.isIE&&(a="-ms-"));return a}();dhx.env.transformPrefix=dhx.env.transformCSSPrefix.replace(/-/gi,"");dhx.env.transitionEnd=dhx.env.transformCSSPrefix=="-Moz-"?"transitionend":dhx.env.transformPrefix+"TransitionEnd"})();
dhx.env.svg=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")}();
dhx.html={create:function(a,b,c){var b=b||{},d=document.createElement(a),e;for(e in b)d.setAttribute(e,b[e]);if(b.style)d.style.cssText=b.style;if(b["class"])d.className=b["class"];if(c)d.innerHTML=c;return d},getValue:function(a){a=dhx.toNode(a);return!a?"":dhx.isNotDefined(a.value)?a.innerHTML:a.value},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else a&&a.parentNode&&a.parentNode.removeChild(a)},insertBefore:function(a,b,c){a&&(b&&b.parentNode?b.parentNode.insertBefore(a,
b):c.appendChild(a))},locate:function(a,b){if(a.tagName)var c=a;else a=a||event,c=a.target||a.srcElement;for(;c;){if(c.getAttribute){var d=c.getAttribute(b);if(d)return d}c=c.parentNode}return null},offset:function(a){if(a.getBoundingClientRect){var b=a.getBoundingClientRect(),c=document.body,d=document.documentElement,e=window.pageYOffset||d.scrollTop||c.scrollTop,g=window.pageXOffset||d.scrollLeft||c.scrollLeft,h=d.clientTop||c.clientTop||0,f=d.clientLeft||c.clientLeft||0,i=b.top+e-h,j=b.left+g-
f;return{y:Math.round(i),x:Math.round(j)}}else{for(j=i=0;a;)i+=parseInt(a.offsetTop,10),j+=parseInt(a.offsetLeft,10),a=a.offsetParent;return{y:i,x:j}}},pos:function(a){a=a||event;if(a.pageX||a.pageY)return{x:a.pageX,y:a.pageY};var b=dhx.env.isIE&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:a.clientX+b.scrollLeft-b.clientLeft,y:a.clientY+b.scrollTop-b.clientTop}},preventEvent:function(a){a&&a.preventDefault&&a.preventDefault();return dhx.html.stopEvent(a)},stopEvent:function(a){(a||
event).cancelBubble=!0;return!1},addCss:function(a,b){a.className+=" "+b},removeCss:function(a,b){a.className=a.className.replace(RegExp(" "+b,"g"),"")}};dhx.ready=function(a){this.aa?a.call():this.v.push(a)};dhx.v=[];
(function(){var a=document.getElementsByTagName("SCRIPT");if(a.length)a=(a[a.length-1].getAttribute("src")||"").split("/"),a.splice(a.length-1,1),dhx.codebase=a.slice(0,a.length).join("/")+"/";dhx.event(window,"load",function(){dhx.callEvent("onReady",[]);dhx.delay(function(){dhx.aa=!0;for(var a=0;a<dhx.v.length;a++)dhx.v[a].call();dhx.v=[]})})})();dhx.ui={};dhx.ui.zIndex=function(){return dhx.ui.ea++};dhx.ui.ea=1;
dhx.ready(function(){dhx.event(document.body,"click",function(a){dhx.callEvent("onClick",[a||event])})});dhx.ajax=function(a,b,c){if(arguments.length!==0){var d=new dhx.ajax;if(c)d.master=c;d.get(a,null,b)}return!this.getXHR?new dhx.ajax:this};
dhx.ajax.prototype={getXHR:function(){return dhx.env.isIE?new ActiveXObject("Microsoft.xmlHTTP"):new XMLHttpRequest},send:function(a,b,c){var d=this.getXHR();typeof c=="function"&&(c=[c]);if(typeof b=="object"){var e=[],g;for(g in b){var h=b[g];if(h===null||h===dhx.undefined)h="";e.push(g+"="+encodeURIComponent(h))}b=e.join("&")}b&&!this.post&&(a=a+(a.indexOf("?")!=-1?"&":"?")+b,b=null);d.open(this.post?"POST":"GET",a,!this.da);this.post&&d.setRequestHeader("Content-type","application/x-www-form-urlencoded");
var f=this;d.onreadystatechange=function(){if(!d.readyState||d.readyState==4){if(c&&f)for(var a=0;a<c.length;a++)c[a]&&c[a].call(f.master||f,d.responseText,d.responseXML,d);c=f=f.master=null}};d.send(b||null);return d},get:function(a,b,c){this.post=!1;return this.send(a,b,c)},post:function(a,b,c){this.post=!0;return this.send(a,b,c)},sync:function(){this.da=!0;return this}};
dhx.AtomDataLoader={c:function(a){this.data={};if(a)this.a.datatype=a.datatype||"json",this.w.push(this.X)},X:function(){this.P=!0;this.a.url&&this.url_setter(this.a.url);this.a.data&&this.data_setter(this.a.data)},url_setter:function(a){if(!this.P)return a;this.load(a,this.a.datatype);return a},data_setter:function(a){if(!this.P)return a;this.parse(a,this.a.datatype);return!0},load:function(a,b,c){this.callEvent("onXLS",[]);typeof b=="string"?(this.data.driver=dhx.DataDriver[b],b=c):this.data.driver=
dhx.DataDriver.json;dhx.ajax(a,[this.D,b],this)},parse:function(a,b){this.callEvent("onXLS",[]);this.data.driver=dhx.DataDriver[b||"json"];this.D(a,null)},D:function(a,b){var c=this.data.driver,d=c.getRecords(c.toObject(a,b))[0];this.data=c?c.getDetails(d):a;this.callEvent("onXLE",[])},q:function(a){if(!this.a.dataFeed||this.B||!a)return!0;var b=this.a.dataFeed,b=b+(b.indexOf("?")==-1?"?":"&")+"action=get&id="+encodeURIComponent(a.id||a);this.callEvent("onXLS",[]);dhx.ajax(b,function(a){this.B=!0;
this.setValues(dhx.DataDriver.json.toObject(a)[0]);this.B=!1;this.callEvent("onXLE",[])},this);return!1}};dhx.DataDriver={};dhx.DataDriver.json={toObject:function(a){a||(a="[]");if(typeof a=="string")eval("dhx.temp="+a),a=dhx.temp;if(a.data){var b=a.data;b.pos=a.pos;b.total_count=a.total_count;a=b}return a},getRecords:function(a){return a&&!(a instanceof Array)?[a]:a},getDetails:function(a){return a},getInfo:function(a){return{k:a.total_count||0,i:a.pos||0}}};
dhx.DataDriver.json_ext={toObject:function(a){a||(a="[]");if(typeof a=="string"){var b;eval("temp="+a);dhx.temp=[];for(var c=b.header,a=0;a<b.data.length;a++){for(var d={},e=0;e<c.length;e++)typeof b.data[a][e]!="undefined"&&(d[c[e]]=b.data[a][e]);dhx.temp.push(d)}return dhx.temp}return a},getRecords:function(a){return a&&!(a instanceof Array)?[a]:a},getDetails:function(a){return a},getInfo:function(a){return{k:a.total_count||0,i:a.pos||0}}};
dhx.DataDriver.html={toObject:function(a){if(typeof a=="string"){var b=null;a.indexOf("<")==-1&&(b=dhx.toNode(a));if(!b)b=document.createElement("DIV"),b.innerHTML=a;return b.getElementsByTagName(this.tag)}return a},getRecords:function(a){return a.tagName?a.childNodes:a},getDetails:function(a){return dhx.DataDriver.xml.tagToObject(a)},getInfo:function(){return{k:0,i:0}},tag:"LI"};
dhx.DataDriver.jsarray={toObject:function(a){return typeof a=="string"?(eval("dhx.temp="+a),dhx.temp):a},getRecords:function(a){return a},getDetails:function(a){for(var b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{k:0,i:0}}};
dhx.DataDriver.csv={toObject:function(a){return a},getRecords:function(a){return a.split(this.row)},getDetails:function(a){for(var a=this.stringToArray(a),b={},c=0;c<a.length;c++)b["data"+c]=a[c];return b},getInfo:function(){return{k:0,i:0}},stringToArray:function(a){for(var a=a.split(this.cell),b=0;b<a.length;b++)a[b]=a[b].replace(/^[ \t\n\r]*(\"|)/g,"").replace(/(\"|)[ \t\n\r]*$/g,"");return a},row:"\n",cell:","};
dhx.DataDriver.xml={toObject:function(a,b){return b&&(b=this.checkResponse(a,b))?b:typeof a=="string"?this.fromString(a):a},getRecords:function(a){return this.xpath(a,this.records)},records:"/*/item",getDetails:function(a){return this.tagToObject(a,{})},getInfo:function(a){return{k:a.documentElement.getAttribute("total_count")||0,i:a.documentElement.getAttribute("pos")||0}},xpath:function(a,b){if(window.XPathResult){var c=a;if(a.nodeName.indexOf("document")==-1)a=a.ownerDocument;for(var d=[],e=a.evaluate(b,
c,null,XPathResult.ANY_TYPE,null),a=e.iterateNext();a;)d.push(a),a=e.iterateNext();return d}else{d=!0;try{typeof a.selectNodes=="undefined"&&(d=!1)}catch(g){}return d?a.selectNodes(b):(d=b.split("/").pop(),a.getElementsByTagName(d))}},tagToObject:function(a,b){var b=b||{},c=!1,d=a.attributes;if(d&&d.length){for(var e=0;e<d.length;e++)b[d[e].name]=d[e].value;c=!0}d=a.childNodes;for(e=0;e<d.length;e++)if(d[e].nodeType==1){var g=d[e].tagName;typeof b[g]!="undefined"?(b[g]instanceof Array||(b[g]=[b[g]]),
b[g].push(this.tagToObject(d[e],{}))):b[d[e].tagName]=this.tagToObject(d[e],{});c=!0}if(!c)return this.nodeValue(a);b.value=this.nodeValue(a);return b},nodeValue:function(a){return a.firstChild?a.firstChild.data:""},fromString:function(a){if(window.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");if(window.ActiveXObject){var b=new ActiveXObject("Microsoft.xmlDOM");b.loadXML(a);return b}},checkResponse:function(a,b){if(b&&b.firstChild&&b.firstChild.tagName!="parsererror")return b;if(a=
this.fromString(a.replace(/^[\s]+/,"")))return a}};
dhx.DataLoader=dhx.proto({c:function(a){a=a||"";name="DataStore";this.data=a.datastore||new dhx.DataStore;this.F=this.data.attachEvent("onStoreLoad",dhx.bind(this.V,this))},load:function(a){dhx.AtomDataLoader.load.apply(this,arguments);if(!this.data.feed)this.data.url=a,this.data.feed=function(b,c){if(this.u)return this.u=[b,c];else this.u=!0;this.load(a+(a.indexOf("?")==-1?"?":"&")+"start="+b+"&count="+c,function(){var a=this.u;this.u=!1;typeof a=="object"?this.data.feed.apply(this,a):this.showItem&&
this.dataCount()>b+1&&this.showItem(this.idByIndex(b+1))})}},loadNext:function(a,b){this.data.feed&&this.data.feed.call(this,b||this.dataCount(),a)},D:function(a,b){this.data.$(this.data.driver.toObject(a,b));this.callEvent("onXLE",[]);if(this.F)this.data.detachEvent(this.F),this.F=null},scheme_setter:function(a){this.data.scheme(a)},dataFeed_setter:function(a){this.data.attachEvent("onBeforeFilter",dhx.bind(function(a,c){if(this.a.dataFeed){var d={};if(a||d){if(typeof a=="function"){if(!c)return;
a(c,d)}else d={text:c};this.clearAll();var a=this.a.dataFeed,e=[],g;for(g in d)e.push("dhx_filter["+g+"]="+encodeURIComponent(d[g]));this.load(a+(a.indexOf("?")<0?"?":"&")+e.join("&"),this.a.datatype);return!1}}},this));return a},V:function(){if(this.a.ready){var a=dhx.toFunctor(this.a.ready);a&&a.call&&a.apply(this,arguments)}}},dhx.AtomDataLoader).prototype;dhx.DataStore=function(){this.name="DataStore";dhx.extend(this,dhx.EventSystem);this.setDriver("xml");this.pull={};this.order=dhx.toArray()};
dhx.DataStore.prototype={setDriver:function(a){this.driver=dhx.DataDriver[a]},$:function(a){this.callEvent("onParse",[this.driver,a]);this.d&&this.filter();var b=this.driver.getInfo(a),c=this.driver.getRecords(a),d=(b.i||0)*1;if(d===0&&this.order[0])d=this.order.length;for(var e=0,g=0;g<c.length;g++){var h=this.driver.getDetails(c[g]),f=this.id(h);this.pull[f]||(this.order[e+d]=f,e++);this.pull[f]=h;this.extraParser&&this.extraParser(h);this.e&&(this.e.$init?this.e.$init(h):this.e.$update&&this.e.$update(h))}if(!this.order[b.k-
1])this.order[b.k-1]=dhx.undefined;this.callEvent("onStoreLoad",[this.driver,a]);this.refresh()},id:function(a){return a.id||(a.id=dhx.uid())},changeId:function(a,b){this.pull[b]=this.pull[a];this.pull[b].id=b;this.order[this.order.find(a)]=b;this.d&&(this.d[this.d.find(a)]=b);this.callEvent("onIdChange",[a,b]);this.ca&&this.ca(a,b);delete this.pull[a]},item:function(a){return this.pull[a]},update:function(a,b){this.e&&this.e.$update&&this.e.$update(b);if(this.callEvent("onBeforeUpdate",[a,b])===
!1)return!1;this.pull[a]=b;this.refresh(a)},refresh:function(a){this.R||(a?this.callEvent("onStoreUpdated",[a,this.pull[a],"update"]):this.callEvent("onStoreUpdated",[null,null,null]))},silent:function(a,b){this.R=!0;a.call(b||this);this.R=!1},getRange:function(a,b){a=a?this.indexById(a):this.startOffset||0;b?b=this.indexById(b):(b=Math.min(this.endOffset||Infinity,this.dataCount()-1),b<0&&(b=0));if(a>b)var c=b,b=a,a=c;return this.getIndexRange(a,b)},getIndexRange:function(a,b){for(var b=Math.min(b||
Infinity,this.dataCount()-1),c=dhx.toArray(),a=a||0;a<=b;a++)c.push(this.item(this.order[a]));return c},dataCount:function(){return this.order.length},exists:function(a){return!!this.pull[a]},move:function(a,b){if(!(a<0||b<0)){var c=this.idByIndex(a),d=this.item(c);this.order.removeAt(a);this.order.insertAt(c,Math.min(this.order.length,b));this.callEvent("onStoreUpdated",[c,d,"move"])}},scheme:function(a){this.e=a},sync:function(a,b,c){typeof b!="function"&&(c=b,b=null);if(dhx.debug_bind)this.debug_sync_master=
a;if(a.name!="DataStore")a=a.data;var d=dhx.bind(function(){this.order=dhx.toArray([].concat(a.order));this.d=null;this.pull=a.pull;b&&this.silent(b);this.M&&this.M();c?c=!1:this.refresh()},this);a.attachEvent("onStoreUpdated",d);d()},add:function(a,b){if(this.e){var a=a||{},c;for(c in this.e)a[c]=a[c]||this.e[c];this.e.$init?this.e.$init(a):this.e.$update&&this.e.$update(a)}c=this.id(a);var d=this.dataCount();if(dhx.isNotDefined(b)||b<0)b=d;b>d&&(b=Math.min(this.order.length,b));if(this.callEvent("onBeforeAdd",
[c,a,b])===!1)return!1;if(this.exists(c))return null;this.pull[c]=a;this.order.insertAt(c,b);if(this.d){var e=this.d.length;!b&&this.order.length&&(e=0);this.d.insertAt(c,e)}this.callEvent("onafterAdd",[c,b]);this.callEvent("onStoreUpdated",[c,a,"add"]);return c},remove:function(a){if(a instanceof Array)for(var b=0;b<a.length;b++)this.remove(a[b]);else{if(this.callEvent("onBeforeDelete",[a])===!1)return!1;if(!this.exists(a))return null;b=this.item(a);this.order.remove(a);this.d&&this.d.remove(a);
delete this.pull[a];this.callEvent("onafterdelete",[a]);this.callEvent("onStoreUpdated",[a,b,"delete"])}},clearAll:function(){this.pull={};this.order=dhx.toArray();this.d=null;this.callEvent("onClearAll",[]);this.refresh()},idByIndex:function(a){return this.order[a]},indexById:function(a){return a=this.order.find(a)},next:function(a,b){return this.order[this.indexById(a)+(b||1)]},first:function(){return this.order[0]},last:function(){return this.order[this.order.length-1]},previous:function(a,b){return this.order[this.indexById(a)-
(b||1)]},sort:function(a,b,c){var d=a;typeof a=="function"?d={as:a,dir:b}:typeof a=="string"&&(d={by:a,dir:b,as:c});var e=[d.by,d.dir,d.as];if(this.callEvent("onbeforesort",e)){if(this.order.length){var g=dhx.sort.create(d),h=this.getRange(this.first(),this.last());h.sort(g);this.order=h.map(function(a){return this.id(a)},this)}this.refresh();this.callEvent("onaftersort",e)}},filter:function(a,b,c){if(this.callEvent("onBeforeFilter",[a,b])){if(this.d&&!c)this.order=this.d,delete this.d;if(this.order.length){if(a){var d=
a,b=b||"";typeof a=="string"&&(a=dhx.Template(a),b=b.toString().toLowerCase(),d=function(b,c){return a(b).toLowerCase().indexOf(c)!=-1});for(var e=dhx.toArray(),g=0;g<this.order.length;g++){var h=this.order[g];d(this.item(h),b)&&e.push(h)}if(!c)this.d=this.order;this.order=e}this.refresh();this.callEvent("onAfterFilter",[])}}},each:function(a,b){for(var c=0;c<this.order.length;c++)a.call(b||this,this.item(this.order[c]))},provideApi:function(a,b){this.debug_bind_master=a;b&&this.mapEvent({onbeforesort:a,
onaftersort:a,onbeforeadd:a,onafteradd:a,onbeforedelete:a,onafterdelete:a,onbeforeupdate:a});for(var c="sort,add,remove,exists,idByIndex,indexById,item,update,refresh,dataCount,filter,next,previous,clearAll,first,last,serialize,sync".split(","),d=0;d<c.length;d++)a[c[d]]=dhx.methodPush(this,c[d])},serialize:function(){for(var a=this.order,b=[],c=0;c<a.length;c++)b.push(this.pull[a[c]]);return b}};
dhx.sort={create:function(a){return dhx.sort.dir(a.dir,dhx.sort.by(a.by,a.as))},as:{"int":function(a,b){a*=1;b*=1;return a>b?1:a<b?-1:0},string_strict:function(a,b){a=a.toString();b=b.toString();return a>b?1:a<b?-1:0},string:function(a,b){a=a.toString().toLowerCase();b=b.toString().toLowerCase();return a>b?1:a<b?-1:0}},by:function(a,b){if(!a)return b;typeof b!="function"&&(b=dhx.sort.as[b||"string"]);a=dhx.Template(a);return function(c,d){return b(a(c),a(d))}},dir:function(a,b){return a=="asc"?b:
function(a,d){return b(a,d)*-1}}};
(function(){var a={};dhx.Template=function(b){if(typeof b=="function")return b;if(a[b])return a[b];b=(b||"").toString();if(b.indexOf("->")!=-1)switch(b=b.split("->"),b[0]){case "html":b=dhx.html.getValue(b[1]);break;case "http":b=(new dhx.ajax).sync().get(b[1],{uid:dhx.uid()}).responseText}b=(b||"").toString();b=b.replace(/(\r\n|\n)/g,"\\n");b=b.replace(/(\")/g,'\\"');b=b.replace(/\{obj\.([^}?]+)\?([^:]*):([^}]*)\}/g,'"+(obj.$1?"$2":"$3")+"');b=b.replace(/\{common\.([^}\(]*)\}/g,"\"+(common.$1||'')+\"");
b=b.replace(/\{common\.([^\}\(]*)\(\)\}/g,'"+(common.$1?common.$1(obj,common):"")+"');b=b.replace(/\{obj\.([^}]*)\}/g,"\"+(obj.$1||'')+\"");b=b.replace(/#([$a-z0-9_\[\]]+)#/gi,"\"+(obj.$1||'')+\"");b=b.replace(/\{obj\}/g,'"+obj+"');b=b.replace(/\{-obj/g,"{obj");b=b.replace(/\{-common/g,"{common");b='return "'+b+'";';try{Function("obj","common",b)}catch(c){}return a[b]=Function("obj","common",b)};dhx.Template.empty=function(){return""};dhx.Template.bind=function(a){return dhx.bind(dhx.Template(a),
this)};dhx.Type=function(a,c){if(a.r){if(!a.m)a.m=[];a.m.push(c)}else{if(typeof a=="function")a=a.prototype;if(!a.types)a.types={"default":a.type},a.type.name="default";var d=c.name,e=a.type;d&&(e=a.types[d]=dhx.copy(a.type));for(var g in c)e[g]=g.indexOf("template")===0?dhx.Template(c[g]):c[g];return d}}})();
dhx.Settings={c:function(){this.a=this.config={}},define:function(a,b){return typeof a=="object"?this.N(a):this.J(a,b)},J:function(a,b){var c=this[a+"_setter"];return this.a[a]=c?c.call(this,b,a):b},N:function(a){if(a)for(var b in a)this.J(b,a[b])},O:function(a,b){var c={};b&&(c=dhx.extend(c,b));typeof a=="object"&&!a.tagName&&dhx.extend(c,a,!0);this.N(c)},Y:function(a,b){for(var c in b)switch(typeof a[c]){case "object":a[c]=this.Y(a[c]||{},b[c]);break;case "undefined":a[c]=b[c]}return a}};
dhx.BaseBind={bind:function(a,b,c){typeof a=="string"&&(a=dhx.ui.get(a));a.b&&a.b();this.b&&this.b();a.getBindData||dhx.extend(a,dhx.BindSource);if(!this.T){var d=this.render;if(this.filter){var e=this.a.id;this.data.M=function(){a.p[e]=!1}}this.render=function(){if(!this.K)return this.K=!0,this.callEvent("onBindRequest"),this.K=!1,d.call(this)};if(this.getValue||this.getValues)this.save=function(){this.validate&&!this.validate()||a.setBindData(this.getValue?this.getValue:this.getValues(),this.a.id)};
this.T=!0}a.addBind(this.a.id,b,c);this.attachEvent(this.touchable?"onAfterRender":"onBindRequest",function(){a.getBindData(this.a.id)});this.isVisible(this.a.id)&&this.refresh()}};
dhx.BindSource={c:function(){this.o={};this.p={};this.A={};this.U(this)},setBindData:function(a,b){b&&(this.A[b]=!0);if(this.setValue)this.setValue(a);else if(this.setValues)this.setValues(a);else{var c=this.getCursor();c&&(a=dhx.extend(this.item(c),a,!0),this.update(c,a))}this.callEvent("onBindUpdate",[a,b]);this.save&&this.save();b&&(this.A[b]=!1)},getBindData:function(a,b){if(!this.p[a]){var c=dhx.ui.get(a);c.isVisible(c.a.id)&&(this.p[a]=!0,this.z(c,this.o[a][0],this.o[a][1]),b&&c.filter&&c.refresh())}},
addBind:function(a,b,c){this.o[a]=[b,c]},U:function(a){a.filter?dhx.extend(this,dhx.CollectionBind):a.setValue?dhx.extend(this,dhx.ValueBind):dhx.extend(this,dhx.RecordBind)},l:function(){for(var a in this.o)this.A[a]||(this.p[a]=!1,this.getBindData(a,!0))},H:function(a,b,c){a.setValue?a.setValue(c?c[b]:c):a.filter?a.data.silent(function(){this.filter(b,c)}):!c&&a.clear?a.clear():a.q(c)&&a.setValues(dhx.copy(c))}};
dhx.DataValue=dhx.proto({name:"DataValue",isVisible:function(){return!0},c:function(a){a=(this.data=a)&&a.id?a.id:dhx.uid();this.a={id:a};dhx.ui.views[a]=this},setValue:function(a){this.data=a;this.callEvent("onChange",[a])},getValue:function(){return this.data},refresh:function(){this.callEvent("onBindRequest")}},dhx.EventSystem,dhx.BaseBind);
dhx.DataRecord=dhx.proto({name:"DataRecord",isVisible:function(){return!0},c:function(a){this.data=a||{};a=a&&a.id?a.id:dhx.uid();this.a={id:a};dhx.ui.views[a]=this},getValues:function(){return this.data},setValues:function(a){this.data=a;this.callEvent("onChange",[a])},refresh:function(){this.callEvent("onBindRequest")}},dhx.EventSystem,dhx.BaseBind);
dhx.DataCollection=dhx.proto({name:"DataCollection",isVisible:function(){return!this.data.order.length&&!this.data.d&&!this.a.dataFeed?!1:!0},c:function(a){this.data.provideApi(this,!0);a=a&&a.id?a.id:dhx.uid();this.a.id=a;dhx.ui.views[a]=this;this.data.attachEvent("onStoreLoad",dhx.bind(function(){this.callEvent("onBindRequest",[])},this))},refresh:function(){this.callEvent("onBindRequest",[])}},dhx.EventSystem,dhx.DataLoader,dhx.BaseBind,dhx.Settings);
dhx.ValueBind={c:function(){this.attachEvent("onChange",this.l)},z:function(a,b,c){var d=this.getValue()||"";c&&(d=c(d));if(a.setValue)a.setValue(d);else if(a.filter)a.data.silent(function(){this.filter(b,d)});else{var e={};e[b]=d;a.q(d)&&a.setValues(e)}}};dhx.RecordBind={c:function(){this.attachEvent("onChange",this.l)},z:function(a,b){var c=this.getValues()||null;this.H(a,b,c)}};
dhx.CollectionBind={c:function(){this.h=null;this.attachEvent("onSelectChange",function(){this.setCursor(this.getSelected())});this.attachEvent("onAfterCursorChange",this.l);this.data.attachEvent("onStoreUpdated",dhx.bind(function(a){a&&a==this.getCursor()&&this.l()},this));this.data.attachEvent("onClearAll",dhx.bind(function(){this.h=null},this));this.data.attachEvent("onIdChange",dhx.bind(function(a,b){if(this.h==a)this.h=b},this))},setCursor:function(a){if(a!=this.h&&this.item(a))this.callEvent("onBeforeCursorChange",
[this.h]),this.h=a,this.callEvent("onAfterCursorChange",[a])},getCursor:function(){return this.h},z:function(a,b){var c=this.item(this.getCursor())||null;this.H(a,b,c)}};if(!dhx.ui.views)dhx.ui.views={},dhx.ui.get=function(a){return a.a?a:dhx.ui.views[a]};
dhtmlXDataStore=function(a){var a=new dhx.DataCollection(a),b="_dp_init";a[b]=function(a){var b="_methods";a[b]=["dummy","dummy","changeId","dummy"];this.data.Z={add:"inserted",update:"updated","delete":"deleted"};this.data.attachEvent("onStoreUpdated",function(b,d,h){b&&!a.Q&&a.setUpdated(b,!0,this.Z[h])});b="_getRowData";a[b]=function(a){var b=this.obj.data.item(a),a={id:a,"!nativeeditor_status":this.obj.getUserData(a)};if(b)for(var c in b)c.indexOf("_")!==0&&(a[c]=b[c]);return a};this.changeId=
function(b,d){this.data.changeId(b,d);a.Q=!0;this.data.callEvent("onStoreUpdated",[d,this.item(d),"update"]);a.Q=!1};b="_clearUpdateFlag";a[b]=function(){};this.S={}};a.dummy=function(){};a.setUserData=function(a,b,e){this.S[a]=e};a.getUserData=function(a){return this.S[a]};return a};
if(window.dhtmlXDataView)dhtmlXDataView.prototype.b=function(){this.isVisible=function(){return!this.data.order.length&&!this.data.d&&!this.a.dataFeed?!1:!0};if(!this.a.id)this.a.id=dhx.uid();dhx.ui.views[this.a.id]=this};if(window.dhtmlXChart)dhtmlXChart.prototype.b=function(){this.isVisible=function(){return!this.data.order.length&&!this.data.ga&&!this.a.dataFeed?!1:!0};if(!this.a.id)this.a.id=dhx.uid();dhx.ui.views[this.a.id]=this};
dhx.BaseBind.legacyBind=function(){return dhx.BaseBind.bind.apply(this,arguments)};dhx.BaseBind.legacySync=function(a){this.b&&this.b();a.b&&a.b();this.attachEvent("onAfterEditStop",function(a){this.save(a);return!0});this.save=function(b){b||(b=this.getCursor());var c=this.item(b),d=a.item(b),e;for(e in c)e.indexOf("$")!==0&&(d[e]=c[e]);a.refresh(b)};return this.data.sync.apply(this.data,arguments)};
if(window.dhtmlXForm)dhtmlXForm.prototype.bind=function(){dhx.BaseBind.bind.apply(this,arguments)},dhtmlXForm.prototype.b=function(){if(dhx.isNotDefined(this.a))this.a={id:dhx.uid(),dataFeed:this.j},dhx.ui.views[this.a.id]=this},dhtmlXForm.prototype.q=function(a){if(!this.a.dataFeed||this.B||!a)return!0;var b=this.a.dataFeed,b=b+(b.indexOf("?")==-1?"?":"&")+"action=get&id="+encodeURIComponent(a.id||a);this.load(b);return!1},dhtmlXForm.prototype.setValues=dhtmlXForm.prototype.setFormData,dhtmlXForm.prototype.getValues=
function(){return this.getFormData(!1,!0)},dhtmlXForm.prototype.dataFeed=function(a){this.a?this.a.dataFeed=a:this.j=a},dhtmlXForm.prototype.refresh=dhtmlXForm.prototype.isVisible=function(){return!0};
if(window.dhtmlXCombo)dhtmlXCombo.prototype.bind=function(){dhx.BaseBind.bind.apply(this,arguments)},dhtmlXCombo.prototype.dataFeed=function(a){this.a?this.a.dataFeed=a:this.j=a},dhtmlXCombo.prototype.sync=function(a){this.b&&this.b();a.b&&a.b();var b=this,c=function(){b.clearAll();b.addOption(this.serialize())};a.data.attachEvent("onStoreUpdated",function(){c.call(this)});a.data.attachEvent("onIdChange",function(a,c){b.changeOptionId(a,c)});c.call(a)},dhtmlXCombo.prototype.b=function(){if(dhx.isNotDefined(this.a))this.a=
{id:dhx.uid(),dataFeed:this.j},dhx.ui.views[this.a.id]=this,this.data={silent:dhx.bind(function(a){a.call(this)},this)},dhtmlxEventable(this.data),this.attachEvent("onChange",function(){this.callEvent("onSelectChange",[this.getSelectedValue()])}),this.attachEvent("onXLE",function(){this.callEvent("onBindRequest",[])})},dhtmlXCombo.prototype.item=function(){return this.ha},dhtmlXCombo.prototype.getSelected=function(){return this.getSelectedValue()},dhtmlXCombo.prototype.isVisible=function(){return!this.optionsArr.length&&
!this.a.dataFeed?!1:!0},dhtmlXCombo.prototype.refresh=function(){this.render(!0)},dhtmlXCombo.prototype.filter=function(){alert("not implemented")};
if(window.dhtmlXGridObject)dhtmlXGridObject.prototype.bind=function(){dhx.BaseBind.bind.apply(this,arguments)},dhtmlXGridObject.prototype.dataFeed=function(a){this.a?this.a.dataFeed=a:this.j=a},dhtmlXGridObject.prototype.sync=function(a,b){this.b&&this.b();a.b&&a.b();var c=this,d="_parsing",e="_parser",g="_locator",h="_process_store_row",f="_get_store_data";this.save=function(b){b||(b=this.getCursor());dhx.extend(a.item(b),this.item(b),!0);a.refresh(b)};var i=function(a){var b=0;c.s?(b=c.s,c.s=!1):
c.clearAll();if(a!==-1&&(a=this.dataCount())){c[d]=!0;for(var i=b;i<a;i++){var k=this.order[i];if(k&&(!b||!c.rowsBuffer[i]))c.rowsBuffer[i]={idd:k,data:this.pull[k]},c.rowsBuffer[i][e]=c[h],c.rowsBuffer[i][g]=c[f],c.rowsAr[k]=this.pull[k]}if(!c.rowsBuffer[a-1])c.rowsBuffer[a-1]=dhtmlx.undefined,c.xmlFileUrl=c.xmlFileUrl||!0;c.pagingOn?c.changePage():c.ia&&c.fa?c.ja():(c.render_dataset(),c.callEvent("onXLE",[]));c[d]=!1}};a.data.attachEvent("onStoreUpdated",function(a,b,d){d=="delete"?(c.deleteRow(a),
c.data.callEvent("onStoreUpdated",[a,b,d])):d=="update"?(c.callEvent("onSyncUpdate",[b,d]),c.update(a,b),c.data.callEvent("onStoreUpdated",[a,b,d])):d=="add"?(c.callEvent("onSyncUpdate",[b,d]),c.add(a,b),c.data.callEvent("onStoreUpdated",[a,b,d])):i.call(this)});a.data.attachEvent("onStoreLoad",function(b,d){c.xmlFileUrl=a.data.url;c.s=b.getInfo(d).i});a.data.attachEvent("onIdChange",function(a,b){c.changeRowId(a,b)});i(-1);c.attachEvent("onEditCell",function(a,b){a==2&&this.save(b);return!0});c.attachEvent("onDynXLS",
function(b,d){for(var e=b;e<b+d;e++)if(!a.data.order[e])return a.loadNext(d,b),!1;c.s=b;i()});c.attachEvent("onClearAll",function(){var a="_f_rowsBuffer";this[a]=null});b&&b.sort&&c.attachEvent("onBeforeSorting",function(b,d,e){if(d=="connector")return!1;var f=this.getColumnId(b);a.sort("#"+f+"#",e=="asc"?"asc":"desc",d=="int"?d:"string");c.setSortImgState(!0,b,e);return!1});b&&b.filter&&c.attachEvent("onFilterStart",function(b,d){var e="_con_f_used";if(c[e]&&c[e].length)return!1;a.data.silent(function(){a.filter();
for(var e=0;e<b.length;e++)if(d[e]!=""){var f=c.getColumnId(b[e]);a.filter("#"+f+"#",d[e],e!=0)}});a.refresh();return!1});c.clearAndLoad=function(b){a.clearAll();a.load(b)}},dhtmlXGridObject.prototype.b=function(){if(dhx.isNotDefined(this.a)){this.a={id:dhx.uid(),dataFeed:this.j};dhx.ui.views[this.a.id]=this;this.data={silent:dhx.bind(function(a){a.call(this)},this)};dhtmlxEventable(this.data);for(var a="_cCount",b=0;b<this[a];b++)this.columnIds[b]||(this.columnIds[b]="cell"+b);this.attachEvent("onSelectStateChanged",
function(a){this.callEvent("onSelectChange",[a])});this.attachEvent("onSelectionCleared",function(){this.callEvent("onSelectChange",[null])});this.attachEvent("onEditCell",function(a,b){a===2&&this.getCursor&&b&&b==this.getCursor()&&this.l();return!0});this.attachEvent("onXLE",function(){this.callEvent("onBindRequest",[])})}},dhtmlXGridObject.prototype.item=function(a){if(a===null)return null;var b="_attrs",b=dhx.fullCopy(this.getRowById(a)[b]);b.id=a;for(var c=this.getColumnsNum(),d=0;d<c;d++)b[this.columnIds[d]]=
this.cells(a,d).getValue();return b},dhtmlXGridObject.prototype.update=function(a,b){for(var c=0;c<this.columnIds.length;c++){var d=this.columnIds[c];dhx.isNotDefined(b[d])||this.cells(a,c).setValue(b[d])}c="_attrs";a=this.getRowById(a)[c];for(d in b)a[d]=b[d]},dhtmlXGridObject.prototype.add=function(a,b){for(var c=[],d=0;d<this.columnIds.length;d++){var e=this.columnIds[d];c[d]=dhx.isNotDefined(b[e])?"":b[e]}this.addRow(a,c,0);d="_attrs";this.getRowById(a)[d]=dhx.fullCopy(b)},dhtmlXGridObject.prototype.getSelected=
function(){return this.getSelectedRowId()},dhtmlXGridObject.prototype.isVisible=function(){var a="_f_rowsBuffer";return!this.rowsBuffer.length&&!this[a]&&!this.a.dataFeed?!1:!0},dhtmlXGridObject.prototype.refresh=function(){this.render_dataset()},dhtmlXGridObject.prototype.filter=function(a,b){if(this.a.dataFeed){var c={};if(!a&&!b)return;if(typeof a=="function"){if(!b)return;a(b,c)}else dhx.isNotDefined(a)?c=b:c[a]=b;this.clearAll();var d=this.a.dataFeed,e=[],g;for(g in c)e.push("dhx_filter["+g+
"]="+encodeURIComponent(c[g]));this.load(d+(d.indexOf("?")<0?"?":"&")+e.join("&"));return!1}if(b===null)return this.filterBy(0,function(){return!1});this.filterBy(0,function(c,d){return a.call(this,d,b)})};
if(window.dhtmlXTreeObject)dhtmlXTreeObject.prototype.bind=function(){dhx.BaseBind.bind.apply(this,arguments)},dhtmlXTreeObject.prototype.dataFeed=function(a){this.a?this.a.dataFeed=a:this.j=a},dhtmlXTreeObject.prototype.b=function(){if(dhx.isNotDefined(this.a))this.a={id:dhx.uid(),dataFeed:this.j},dhx.ui.views[this.a.id]=this,this.data={silent:dhx.bind(function(a){a.call(this)},this)},dhtmlxEventable(this.data),this.attachEvent("onSelect",function(a){this.callEvent("onSelectChange",[a])}),this.attachEvent("onEdit",
function(a,b){a===2&&b&&b==this.getCursor()&&this.l();return!0})},dhtmlXTreeObject.prototype.item=function(a){return a===null?null:{id:a,text:this.getItemText(a)}},dhtmlXTreeObject.prototype.getSelected=function(){return this.getSelectedItemId()},dhtmlXTreeObject.prototype.isVisible=function(){return!0},dhtmlXTreeObject.prototype.refresh=function(){},dhtmlXTreeObject.prototype.filter=function(a,b){if(this.a.dataFeed){var c={};if(a||b){if(typeof a=="function"){if(!b)return;a(b,c)}else dhx.isNotDefined(a)?
c=b:c[a]=b;this.deleteChildItems(0);var a=this.a.dataFeed,b=[],d;for(d in c)b.push("dhx_filter["+d+"]="+encodeURIComponent(c[d]));this.loadXML(a+(a.indexOf("?")<0?"?":"&")+b.join("&"));return!1}}},dhtmlXTreeObject.prototype.update=function(a,b){dhx.isNotDefined(b.text)||this.setItemText(a,b.text)};dhtmlx.skin="dhx_skyblue";
